JenkinsFile_build_container.groovy

- Supports Regular build or PullRequest build
- Clones Doc repo
- Builds container
- Pushes to Dockerhub or Jenkins for PR build
Issue #1
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>

Initial commit for build_container JenkinsFile

---

Dockerfile

Changing one line to ensure that
setuptools gets implemented correctly
in the Docker image.
[skip-ci]
Closes: #8

Update Dockerfile for Jenkins build

---

LICENSE.md

Update the LICENSE.md file in GitHub
to include the full EPL V2 and
Apache V2 license content.
Closes: #16

Eclipse CQ 15880 IP review

---

docs/xgc.md
docs/xjit.md

Updates to concurrentScavenge option to
include RHEL and Ubuntu support.
Closes: #11

Add guarded storage support on zLinux

---

docs/xgcpolicy.md
docs/xxusenogc.md
mkdocs.yml

A new suboption -Xgcpolicy:nogc.
A new -XX option: -XXUseNoGC
Closes: #30

Add new GC mode JEP318

---

JenkinsFile_build_container.groovy

- Add timeout set to 6 hours
- Add timestamps to console output
- Clean workspace at end of build
- Add tar.gz extension to archive name
Issue #1

Make container build more robust

---

docs/dcomibmlangmanagementosmxbeaniscputime100ns.md
docs/env_var.md
docs/xtrace.md

Links to other topics and links to
sections within topics.
Closes: #43

Fix broken links

---

docs/xxusecontainersupport.md
mkdocs.yml
theme/base.html

File xxusecontainersupport.md added and .yml file updated
(base.html also tweaked to remove GitHub edit 'pencil' icon from H1 headers)
Fixes #24

Add new -XX topic for container support

---

docs/xverify.md

Correct usage docs for -Xverify

---

docs/cmdline_specifying.md
docs/env_var.md
docs/messages_intro.md
docs/openj9_directories.md
docs/tool_jdmpview.md
docs/tool_traceformat.md
docs/xceehdlr.md
docs/xcodecachetotal.md
docs/xdump.md
docs/xgc.md
docs/xgcpolicy.md
docs/xlpobjectheap.md
docs/xmine.md
docs/xminf.md
docs/xmint.md
docs/xms.md
docs/xoptionsfile.md
docs/xrs.md
docs/xscminaot.md
docs/xshareclasses.md
docs/xsignal.md
docs/xtrace.md
docs/xxmaxdirectmemorysize.md
docs/xxreducecpumonitoroverhead.md
docs/xxshareclassesenablebci.md
docs/xxverboseverification.md

Mostly markdown formatting issues
across a range of topics.

Edits following review

---

docs/index.md
docs/openj9_support.md

Adding operating system support to the
support statement.
Closes: #41 

Add OS support tables

---

docs/version0.9.md

Add a what's new topic for v0.9.0 to list
notable changes from v0.8.0.
Closes: #27

What's new topic to support OpenJ9 v0.9.0

---

docs/index.md
docs/xshareclasses.md

Update Introduction to link to new topic
areas, GC, SHRC, AOT, Diagnostics etc.
Update the AdoptOpenJDK binary links to
fix change in format.
Improve performance section to add more
cloud optimization info.

General updates to the intro topic and -Xshareclasses

---

JenkinsFile_build_doc.groovy

- Supports PR builds and merge builds
- PR builds push to staging site
- Merge builds push to Eclipse Repo
- Sets commit status of built commit on Github
Fixes #1

Initial commit for JenkinsFile to build doc

---

docs/xxactiveprocessorcount.md
mkdocs.yml

New topic and update to table of contents.
Doc issue:
https://github.com/eclipse/openj9-docs/issues/60

New option -XX:ActiveProcessorCount

---

docs/cmdline_migration.md
mkdocs.yml

Updates to migration topic (cmdline_migration.md)

---

docs/tool_jdmpview.md

Added a few further pieces of useful information
and fixed a few inaccuracies from the original
contribution.

Add additional content / update following review

---

docs/cmdline_migration.md
docs/xdump.md
docs/xxdisableexplicitgc.md
docs/xxheapdumponoutofmemory.md
docs/xxheapdumppath.md
mkdocs.yml

Create new option topics & make updates to migration topic

---

docs/tool_builder.md
docs/xdump.md
docs/xtrace.md
mkdocs.yml

Xdump and Xtrace topics modified and new tool_builder file added to yml

Add links to option-builder tools

---

docs/xgc.md

Changes to -Xgc:concurrentScavenge
Resolves #99

Updates for concurrent scavenge on x86 support

---

docs/xxpositiveidentityhash.md
mkdocs.yml

Add topic for -XX:\[+|-\]PositiveIdentityHash

---

docs/dump_javadump.md

To help users interpret a javadump we are
including (initially) 2 scenarios:
1. A dump produced as a result of a GPF
2. A dump produced as a result of a Java OOM
In each case, we walk through the parts of a
javadump that indicate these types of issues
with some explanations. Input provided by
service.

Include scenarios in the Javadump topic

---

buildenv/Dockerfile
buildenv/requirements.in
buildenv/requirements.txt

Improvements to docker image for building
user documentation.
- implements virtualenv to isolate python packages
- adds pip-tools for managing dependencies

Update build artifacts

---

docs/dump_javadump.md

Enhance the javadump section by providing
2 further scenarios to explain how a javadump
can help you diagnose a native OOM or a
deadlock situation.

Add Native OOM and deadlock scenarios

---

docs/openj9_support.md

fixes: #144
Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

Update 0.15.0 line and add 0.16.0 release

---

docs/dump_javadump.md

Add scenario number 5, how to use a Java dump
to help diagnose a hang.

Add a new Java dump debugging scenario

---

docs/xgc.md

Updates for concurrentScavenge option on -Xgc

---

docs/version0.12.md
docs/version0.9.md
docs/xxusecontainersupport.md

3 instances of broken links found and fixed.

Fix broken links in the user documentation

---

theme/partials/previous_next.html

Remove previous/next links from footer

---

docs/cmdline_migration.md
docs/openj9_newuser.md
mkdocs.yml

Users who are new to OpenJDK with an OpenJ9 VM
often ask what the differences are compared to
HotSpot. This topic helps to summarise the
differences and provide links to other useful
resources.

Add a helpful topic for new users

---

docs/xtunevirtualized.md

We received feedback that the current description
was not adequate. More information is now added to
help a user understand what the option does under
the covers.

Improve description for -Xtune:virtualized

---

docs/version0.13.md
docs/xdump.md
mkdocs.yml

Modify -Xdump for writing to STDOUT/STDERR

---

docs/cmdline_migration.md
docs/openj9_newuser.md
docs/tool_jps.md
docs/tool_migration.md
docs/version0.13.md
mkdocs.yml

Add doc updates for jps tool_jps.md
eclipse#210
Added new topic and updates in two other topics for the new `jps` tool
[skip ci]

210 jps tool

---

docs/dump_javadump.md
docs/version0.13.md

Doc update for https://github.com/eclipse/openj9/issues/1932
Closes: #56

Update Java dump topic with Cgroup changes

---

docs/index.md
docs/xxusecontainersupport.md

Plus fix a typo in xxusecontainersupport.md
[skip ci]

Add links to the different versions of available documentation

---

.github/ISSUE_TEMPLATE/new-documentation-change.md

Add expected release target for new features for planning purposes.
[ci skip]

Add release target to issue template

---

JenkinsFile_build_doc.groovy

Update doc pipeline script to not add a banner for release docs

---

docs/version0.14.md
docs/xxreadipinfoforras.md
mkdocs.yml

Add new -XX:ReadIPInfoForRAS command

---

docs/version0.14.md

Update 0.14 What's new re change to shared classes cache

---

docs/version0.14.md
docs/xxjitinlinewatches.md

Add missing platform to release topic and XX topic

XXJITInlineWatches also supported on x86 macOS

---

docs/version0.15.md
docs/xxjitinlinewatches.md
mkdocs.yml

Option included in 0.14.0 now enabled by default
Closes: #258

Option JITInlineWatches enabled by default

---

docs/djdknativechacha20.md
docs/djdknativecrypto.md
docs/djdknativedigest.md
docs/djdknativegcm.md
docs/djdknativersa.md
docs/introduction.md
docs/version0.15.md
mkdocs.yml

See https://github.com/eclipse/openj9-docs/issues/259
[skip ci]

Doc updates for ChaCha20 and ChaCha20-Poly1305 algorithms

---

docs/xtrace.md

See issue 285 for errros fixed.
Closes: #285

Fix typos and value for process ID

---

docs/xgcpolicy.md
docs/xxusenogc.md

Expand Xgcpolicy:nogc and reference XXusenogc

---

docs/interface_dtfj.md
docs/interface_jvmti.md

See https://github.ibm.com/runtimes/idteam/issues/482
[skip ci]

Make some fixes to the migrated JVMTI/DTFJ docs

---

docs/xdump.md

Table missing %asid and %jobid
Closes: #299

Add missing dump tokens for z/OS

---

docs/tool_jmap.md
docs/version0.15.md
mkdocs.yml

Topic to describe the use of the jmap tool, which is added
for compatibility with the reference implmentation.
Closes: #301

New jmap tool

---

docs/version0.15.md
docs/xxidletuningcompactonidle.md

- link not working in 0.15 release topic
- list items are being wrapped, insert CR

Fix markdown formatting errors

---

docs/version0.15.md

- add missing links
- explain 0.15.1 naming at Adopt

Add links to release binaries

---

docs/version0.15.md
mkdocs.yml

The final tag for the release is 0.15.1

Update 0.15.0 to 0.15.1

---

docs/version0.16.md

Fix link
See https://github.com/eclipse/openj9-docs/issues/305
[skip ci]

Doc updates for Field Watch support on Power

---

docs/version0.16.md
docs/xverify.md

Deprecate -Xverify:none and -noverify in Java 13

---

docs/cmdline_migration.md
docs/xxcompactstrings.md
mkdocs.yml

Document -XX:[+|-]CompactStrings

---

JenkinsFile_build_doc.groovy

Add credentials to Git clone from Eclipse repo

---

JenkinsFile_build_doc.groovy

- There is an issue trying to push from within
the container. The linux user id doesn't match
because of how containers work. There were a few
workaround solutions on SO that didn't fully
resolve the issue for us. As a result we're now
exiting the container before doing the push.
Related #363 #354

Push to Eclipse outside of container

---

docs/version0.17.md
docs/xxshareunsafeclasses.md
mkdocs.yml

Store Unsafe classes in shared class cache (-XX:[+/-]ShareUnsafeClasses)

---

docs/version0.17.md
docs/xshareclasses.md

Fix type SIGBUG -> SIGBUS
Closes: #377

Fix incorrect reference to signal

---

docs/version0.17.md
docs/xfuture.md
docs/xverify.md
docs/xxclassrelationshipverifier.md
mkdocs.yml

New -XX[+|-]ClassRelationshipVerifier command line option

---

docs/version0.17.md
docs/version0.9.md

Remove DDR restriction re 32/64-bit JVMs

---

docs/dump_javadump.md
docs/version0.17.md

HOOKS section behavior change in javadump

---

docs/dump_javadump.md
docs/shrc_diag_util.md

Additional content following #385
- new Java dump output
- new printAllStats and PrintLayerStats output
- updates to descriptions
Closes: #368

Further updates for layered shared classes cache

---

docs/xjit.md

Double fix of #398 to remove enforce option from master.

Remove -Xjit:enableGPU=enforce

---

README.md

- For new users, highlight our Getting Started topic
as a good place to find out more information about
the Eclipse OpenJ9 VM.

Update README to point to Getting Started topic

---

docs/version0.18.md
docs/xshareclasses.md

Add documentation for -Xshareclasses:noTimestampChecks

---

docs/openj9_defaults.md
docs/version0.18.md
docs/xmso.md

Updates for -Xmso 1 MB minimum on z/OS 64-bit

---

CONTRIBUTING.md

Change internal IBM link to external

---

JenkinsFile_build_doc.groovy

- Add a second mkdocs build for releases builds.
Zip up the site directory and push to the
Github repo in the downloads folder.

Push zip to downloads for releases

---

docs/stylesheets/oj9.css
theme/partials/header.html

Signed-off-by: Bazif Khan <bazif.khan@ibm.com>

Hamburger menu in mobile view fixed

---

docs/cmdline_migration.md
docs/version0.18.md
docs/xdump.md
docs/xxexitonoutofmemory.md
mkdocs.yml

Add Xdump:exit agent and ExitOnOutOfMemoryError

---

CONTRIBUTING.md
docs/version0.17.md
docs/xxshareunsafeclasses.md

(Also fix a couple of other little errors.)

Add OpenSSL update for 0.17 into 0.18

---

docs/dcomibmenableclasscaching.md
docs/version0.18.md

Enable LUDCL by default for 0.18.0

---

docs/version0.18.md
docs/xgc.md

Document -Xgc:noConcurrentScavenge

---

buildenv/requirements.in
buildenv/requirements.txt

Upgrade to the latest level of MkDocs, which involves upgrading dependencies too
[skip ci]

Upgrade MkDocs

---

mkdocs.yml

Reinstate Google Analytics

---

docs/stylesheets/oj9.css
theme/partials/header.html

Last fix has minor diffs compared with master, which
do not cause a problem in local builds and
on their own do not look at all significant, but
re-applying files from master to overwrite those in
the 0.17.0 branch to ensure files are identical.

Attempt to fix large header on release docs

---

docs/openj9_support.md
docs/version0.18.md
docs/xdump.md
docs/xtrace.md

Also update openj9_support.md for this release
and fix typo in xtrace .md (see #441)

Tidy version0.18.md

---

docs/version0.18.md
docs/xshareclasses.md

Remove documentation of restriction on multi-layer shared cache.

---

docs/stylesheets/oj9.css

Logo in header adjusted

---

docs/diag_overview.md
docs/interface_lang_management.md
docs/openj9_newuser.md
mkdocs.yml

Add new topic and change links from old content in
IBM Knowledge Center.

Add information about OpenJ9 MXBeans

---

docs/openj9_support.md

Update AIX Java 13 compiler, add XL C++ Runtime prereq

---

docs/version0.18.md
docs/xshareclasses.md

Closes https://github.com/eclipse/openj9-docs/issues/473

Remove experimental from shared cache layer options

---

docs/jitserver.md
docs/version0.18.md
mkdocs.yml

Add JITServer tech preview

---

docs/cmdline_migration.md
docs/djavalangstringsubstringnocopy.md
docs/version0.18.md
mkdocs.yml

Document -Djava.lang.string.substring.nocopy

---

docs/openj9_support.md

Remove out of support Windows 7 and 8 (not 8.1)

---

docs/openj9_support.md

Cherry pick of #485 
Closes #484

(0.18.0) Remove out of support Windows 7 and 8 (not 8.1)

---

mkdocs.yml

fixes https://github.com/eclipse/openj9-docs/issues/481
Signed-off-by: Michael Seele <mseele@gmail.com>

fix Version 0.18.0 > 0.18.1

---

docs/dcomibmtoolsattachenable.md
docs/dump_systemdump.md
docs/interface_jvmti.md
docs/messages_intro.md
docs/openj9_defaults.md
docs/xcompressedrefs.md
docs/xgc.md
docs/xlp.md
docs/xshareclasses.md
docs/xxallowvmshutdown.md
docs/xxpagealigndirectmemory.md

Replace redirected URLs with the final URL to avoid
these being flagged repeatedly in test results.

Fix redirects

---

docs/openj9_support.md
docs/version0.19.md
mkdocs.yml

Also adjust mkdocs.yml
and extend 'Eclipse OpenJ9 releases' table in openj9_support.md

Initialise "What's new" topic for 0.19.0 (version0.19.md)

---

docs/openj9_signals.md
mkdocs.yml

Supplement user docs with new signal handling topic,
organised by platform.

Add signal handling information

---

docs/cmdline_migration.md
docs/openj9_newuser.md

Move -Djava.lang.string.substring.nocopy out of compatible options

---

docs/djavalangstringbuffergrowaggressively.md
docs/version0.19.md
mkdocs.yml

Document -Djava.lang.stringBuffer.growAggressively

---

docs/openj9_signals.md
docs/xrs.md
docs/xsigcatch.md
docs/xsigchain.md
docs/xsignal.md

Fix links in the existing doc and add new links between
relevant topics.

Complete work on signal handling

---

docs/version0.19.md

Fix stringbuffer-and-stringbuilder link

---

docs/openj9_support.md

Windows Server 2019 is a supported platform

---

docs/openj9_support.md

zLinux compilation is moved to RHEL 7

---

docs/version0.19.md

Add entry in "What's new" for 0.19.0
Resolves #474

JEP 343 : Packaging Tool - supported platforms

---

docs/cmdline_specifying.md

JAVA_TOOLS_OPTIONS should be JAVA_TOOL_OPTIONS

---

docs/version0.20.md
mkdocs.yml

** Do not merge until 0.19 is split **

WIP Create "What's new" topic for 0.20.0 (version0.20.md)

---

docs/version0.20.md
docs/xxgloballockreservation.md
mkdocs.yml

Closes: #535
Signed-off-by: jimmyk <jimmyk@ca.ibm.com>

Document -XX:+GlobalLockReservation option

---

docs/version0.20.md

- remove templating
- trademark
- minor edits for grammar

Tidy up release notes

---

CONTRIBUTING.md
docs/adoptopenjdk.md
docs/index.md
docs/introduction.md
docs/xverify.md
mkdocs.yml

Change all instances of Java 13 to 14, including icons.

---

docs/openj9_support.md

Remove support for Windows 8.1, Server 2012, but not R2

---

docs/openj9_support.md
docs/version0.21.md
mkdocs.yml

Update mkdocs.yml & openj9_support.md

Create "What's New" topic for 0.21.0

---

docs/xaot.md

Remove statement about shared classes not enabled by default

---

docs/version0.21.md

OSX shared libraries version modified to 1.0.0

---

docs/version0.21.md
docs/xxprintflagsfinal.md
mkdocs.yml

Create new xxprintflagsfinal.md topic and add entry to version0.21.md
Resolves #571

Document -XX:[+/-]PrintFlagsFinal

---

docs/javascripts/oj9.js

Signed-off-by: Bazif Khan <bazif.khan@ibm.com>

API docs mobile view fix

---

docs/allocator.md
docs/gc.md
mkdocs.yml

Allocator info separated into allocator.md and made a sub-topic along with remainder of gc.md

Reorganise topics under "Memory management"

---

docs/openj9_support.md

Update table of releases in openj9_support.md

---

docs/api-conditionhandling.md
docs/api-cuda.md
docs/api-daa.md
docs/api-dtfj.md
docs/api-gpu.md
docs/api-jdk11.md
docs/api-jvm.md
docs/api-langmgmt.md
docs/api-shrc.md
docs/api/jdk11/index.html
docs/api/jdk11/script.js
docs/api/jdk11/search.js
docs/stylesheets/oj9.css

Signed-off-by: Bazif Khan <bazif.khan@ibm.com>

API Docs search and scroll bar fix

---

docs/cmdline_migration.md
docs/djavalangstringbuffergrowaggressively.md
docs/djavalangstringsubstringnocopy.md
docs/version0.18.md
docs/version0.20.md
docs/version0.21.md
docs/xshareclasses.md
docs/xxprintflagsfinal.md

General tidying for 0.21 (2)

---

docs/introduction.md
docs/openj9_support.md

Better advertise jdk14+ requirement for the AIX XL C++ Runtime

---

docs/javascripts/oj9.js
docs/stylesheets/oj9.css

Signed-off-by: Bazif Khan <bazif.khan@ibm.com>

Scroll bar issue fix

---

docs/cmdline_migration.md
docs/openj9_signals.md
docs/version0.21.md
mkdocs.yml

- update "Switching to OpenJ9" topic
- udpate signal handling topic
- tweak what's new to explain the work is for compatibility
Closes: #590

Add  further content for SIGABRT signal handling

---

docs/api-overview.md
docs/openj9_newuser.md

- Add more content to the overview topic to describe usage.
- Link to the API doc from  the "New to OpenJ9" topic.

Improve API overview and add links for new users

---

docs/adoptopenjdk.md
docs/index.md
docs/introduction.md
docs/openj9_support.md

- supported environments
- AdoptOpenJDK topic
- Introduction - build
Closes:  #603

Add OpenJDK 15 support

---

docs/tool_jdmpview.md

Fixes: https://github.com/eclipse/openj9-docs/issues/605

Update jdmpview example gc thread output

---

docs/introduction.md

- improve DAA section in the introduction
- list types of functions you can use
- list benefits
- link to API doc

Add more information for DAA

---

docs/version0.22.md
docs/xxportablesharedcache.md
mkdocs.yml

Issue: https://github.com/eclipse/openj9-docs/issues/615
Signed-off-by: Harry Yu <harryyu1994@gmail.com>

Add -XX:[+|-]PortableSharedCache

---

docs/attachapi.md
docs/dcomibmtoolsattachcommand_timeout.md
docs/dcomibmtoolsattachdirectory.md
docs/dcomibmtoolsattachdisplayname.md
docs/dcomibmtoolsattachid.md
docs/dcomibmtoolsattachlogging.md
docs/dcomibmtoolsattachlogname.md
docs/dcomibmtoolsattachshutdown_timeout.md
mkdocs.yml

Create new topic for Attach API with informatiom about usage, security, configuration.
Modify system property topics for accuracy, completeness and remove links to older material elsewhere.

Add further content for Attach API

---

docs/attachapi.md
docs/dcomibmtoolsattachdirectory.md
docs/dcomibmtoolsattachtimeout.md

Updates mostly to new Attach API tpoic - Add more info from old doc, expand troublshooting section.

Further updates to Attach API topics

---

docs/openj9_defaults.md
docs/version0.22.md
docs/xxportablesharedcache.md
docs/xxusecontainersupport.md

General tidying for 0.22

---

docs/version0.22.md
docs/xxportablesharedcache.md

Added performance note re Z, and modify wording re -XX:[+|-]PortableSharedCache.

More tidying for 0.22.0

---

docs/openj9_support.md
docs/version0.23.md
mkdocs.yml

Create version0.23.md and update openj9_support.md

---

docs/attachapi.md
docs/dcomibmtoolsattachlogging.md

- build errors found and fixed

Fix broken links in AttachAPI topics

---

docs/tool_jdmpview.md

This option is not formally supported and  subject to change.
Update  topic.
Closes: #640

jdmpview !j9help option update

---

docs/attachapi.md
docs/dcomibmtoolsattachlogging.md

Patch release branch to fix broken links

---

docs/index.md

- Fix icon description
- Modify note on IBM contribution
- Modify note on supported environments

Minor updates to About page

---

docs/jitserver.md
docs/version0.23.md

- extended to 64-bit P & Z systems
- update to release topic and JITServer topic
Closes: #660

Extend platform support for JITServer tech preview

---

docs/openj9_support.md
docs/version0.24.md
mkdocs.yml

**To be merged as soon as 0.23 released (and not before!) so that 0.24 updates have a "What's new" page to add to.**

WIP Create version0.24.md and update openj9_support.md

---

docs/version0.24.md
docs/xxportablesharedcache.md

Issue: https://github.com/eclipse/openj9-docs/issues/651
Signed-off-by: Harry Yu <harryyu1994@gmail.com>

Update documentation for PortableSharedCache on Z and Power

---

docs/xxshareanonymousclasses.md

Update doc for -XX:[+|-]ShareAnonymousClasses

---

theme/base.html
theme/partials/social.html

Signed-off-by: Dave Hobbs <dave_hobbs@uk.ibm.com>

Enable Font Awesome icons

---

docs/openj9_support.md

- Refine minimum OS levels
- provide clarity over what is expected to work
- update & roll forward the platform table to show next LTS
Closes: #666

Update support table for clarity

---

docs/xdump.md

Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>

Fix unnecessary trailing tilde

---

JenkinsFile_build_container.groovy
JenkinsFile_build_doc.groovy
jenkinsFile_cleanup_staging.groovy

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=568882

Update Jenkins Credential IDs to new human-readable names

---

docs/cmdline_migration.md
docs/interface_jvmti.md
docs/messages_intro.md
docs/version0.24.md
docs/xlog.md
mkdocs.yml

Issue https://github.com/eclipse/openj9-docs/issues/671

Parse -Xlog:gc variants for compatibility

---

docs/version0.24.md

Allow -Xdump options for jcmd Dump.* commands

---

docs/gc.md
docs/xgcpolicy.md

Further updates for metronome/optavgpause/optthruput GC

---

docs/cmdline_general.md

Add extension section to topic
Closes: #686

Document OpenJ9 extension to -verbose standard option

---

docs/openj9_support.md

Fixes https://github.com/eclipse/openj9-docs/issues/688

Remove support for macOS 10.9

---

docs/openj9_support.md
docs/version0.24.md

Closes https://github.com/eclipse/openj9-docs/issues/662

Update to compile Windows Java 8 with VS2013

---

docs/version0.24.md
docs/xxshareanonymousclasses.md

version0.24.md
- Adjust note re Windows builds for Java 8
- Add note re change for the jextract

Tidying for version 0.24.0

---

docs/gc.md
docs/version0.24.md
docs/xcompressedrefs.md

- fix broken links re renamed allocator.md topic

More tidying for 0.24

---

docs/openj9_support.md

Closes https://github.com/eclipse/openj9-docs/issues/581

Update Mac build information

---

docs/openj9_newuser.md
docs/version0.24.md
docs/xgc.md

- slight reword of -XX:[+|-]ShareAnonymousClasses entry in 0.24 topic
- fixes to GC link titles/targets

Minor edits to finalise release

---

docs/dump_javadump.md
docs/version0.24.md

Add to release topic and update the example shown in the Java dump file.
Closes: #705

Java dump now includes CPU feature information

---

theme/partials/footer.html

Fix broken links in footer

---

theme/partials/footer.html

Refix broken links in footer

---

docs/introduction.md
docs/version0.19.md
docs/version0.25.md

Updated info for jpackage

---

docs/version0.25.md
docs/xxdiagnosesynconvaluebasedclasses.md
mkdocs.yml

Add doc for JEP390 command line options

---

docs/version0.25.md
docs/xdump.md

Fixes https://github.com/eclipse/openj9-docs/issues/724

Add new z/OS dump token %sysname

---

docs/version0.25.md

Fixes https://github.com/eclipse/openj9-docs/issues/739

Switch to mixedrefs builds

---

docs/gc_overview.md
docs/introduction.md
docs/xconcurrentbackground.md

- Fix broken link in GC topic
- Add version icon to jpackage
- Fix sentence fragment

Editorial updates for 0.25.0

---

docs/jitserver.md
docs/version0.24.md

- available since 0.24.0
Closes: #743

Add JITServer helm chart availability

---

docs/vgclog.md
docs/vgclog_examples.md
mkdocs.yml

This PR delivers the following topics:
- Verbose GC Logs
- Log examples [just for Gencon]
Signed-off-by: MelHopper <melanieh@uk.ibm.com>

Added new verbose GC log topics

---

docs/version0.27.md

- Include an entry in the release topic for this update

Add release topic entry for Java dump time zone update

---

docs/shrc.md
docs/shrc_diag_util.md
docs/xscmx.md
docs/xshareclasses.md
docs/xxshareclassesenablebci.md
docs/xxsharedcachehardlimit.md
mkdocs.yml

- Update existing topic on shared classes diag utilities to include verbose options and trace
- Add cache size section to xscmx option topic
- Modify links for various topics to target the new content.

Add shared classes diagnostic information

---

docs/dump_systemdump.md
docs/tool_jdmpview.md
docs/xtrace.md

- fix markdown markup issues
- Add improved links between topics

Editorial updates to diagnostic topics

---

docs/configuring.md

- Recommended resource settings for z/OS

Add z/OS system configuration information

---

docs/version0.27.md

There is already a link on JAVA_OPTIONS, don't need both.

Remove link from "with different behaviour"

---

docs/interface_dtfj.md

Fixes https://github.com/eclipse-openj9/openj9-docs/issues/798
Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>

Add note about requiring the openj9.dtfj module

---

docs/jitserver.md
docs/xxjitserveraddress.md
docs/xxjitserverlocalsynccompiles.md
docs/xxjitserverlogconnections.md
docs/xxjitserverport.md
docs/xxjitservershareromclasses.md
docs/xxjitserversslcert.md
docs/xxjitserversslkey.md
docs/xxjitserversslrootcerts.md
docs/xxjitservertimeout.md
docs/xxrequirejitserver.md
docs/xxusejitserver.md
mkdocs.yml

This commit adds documentation for all the new `-XX` options
that are related to JITServer technology.
Closes: #816

Document -XX options for JITServer

---

docs/introduction.md

Update link to build instructions

---

jenkinsFile_cleanup_staging.groovy

fixes eclipse-openj9/openj9#13949

Use same GH token for api calls

---

docs/version0.30.md
mkdocs.yml

See: eclipse-openj9/openj9/pull/13199
Signed-off-by: Cheng Jin <jincheng@ca.ibm.com>

Doc updates for shared classes cache generation number

---

docs/version0.30.md
docs/xxensurehashed.md
mkdocs.yml

Closes: #826
Signed-off-by: Eric Yang <eric.yang@ibm.com>

Add doc for `-XX:[+|-]EnsureHashed` java option

---

docs/version0.29.1.md
mkdocs.yml

Add 0.29.1 release notes

---

docs/cmdline_specifying.md
docs/dump_systemdump.md
docs/shrc.md
docs/shrc_diag_util.md
docs/version0.10.md
docs/version0.11.md
docs/version0.12.md
docs/version0.13.md
docs/version0.14.md
docs/version0.15.md
docs/version0.16.md
docs/version0.17.md
docs/version0.18.md
docs/version0.19.md
docs/version0.20.md
docs/version0.21.md
docs/version0.22.md
docs/version0.23.md
docs/version0.24.md
docs/version0.25.md
docs/version0.26.md
docs/version0.27.md
docs/version0.29.1.md
docs/version0.29.md
docs/version0.30.md
docs/version0.9.md
docs/xoptionsfile.md
docs/xshareclasses.md
docs/xxenable3164interoperability.md
mkdocs.yml

https://github.com/eclipse-openj9/openj9-docs/issues/832
Signed-off-by: Sujatha sujatha.mohan@ibm.com

Minor fixes

---

docs/xtgc.md

Signed-off-by: Aleksandar Micic <amicic@ca.ibm.com>

Add missing Xtgc options

---

docs/version0.30.md

Release notes for 0.30
Signed-off-by: Aleksandar Micic <amicic@ca.ibm.com>

Balanced GC heap resizing

---

docs/version0.31.md
docs/xxshowhiddenframes.md
mkdocs.yml

Fixes: #887 
Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

Add documentation for `-XX:[+|-]ShowHiddenFrames`

---

docs/xxshowhiddenframes.md

Correct copyright date

---

docs/version0.29.1.md

Closes https://github.com/eclipse-openj9/openj9-docs/issues/821

List features in OpenJDK 17 that apply to OpenJ9

---

docs/version0.31.md

For https://github.com/eclipse-openj9/openj9/pull/13925

Add release note for new SharedClassStatistics API

---

docs/shrc_diag_util.md
docs/xceehdlr.md
docs/xtrace.md
docs/xxensurehashed.md
docs/xxmaxdirectmemorysize.md

https://github.com/eclipse-openj9/openj9-docs/issues/915

Fixed the broken links and made minor updates

---

docs/jitserver.md
docs/version0.32.md

Issue: #927
Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

Starting with release 0.32.0 JITServer is supported on zLinux as well

---

docs/openj9_support.md
docs/version0.33.md

See https://github.com/eclipse-openj9/openj9/pull/15233

Update to reflect jdk8 Windows compilation with VS2017

---

docs/version0.33.md

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

Add a note about cgroup v2 support in the 0.33 release

---

docs/xxjitserversslcert.md

https://github.com/eclipse-openj9/openj9-docs/issues/930
Updated based on the review comment.

Update to reflect JITServer support for openssl 3

---

docs/attachapi.md
docs/version0.25.md

https://github.com/eclipse-openj9/openj9-docs/issues/991
Updated the suggested changes.

Update for inclusive language

---

docs/version0.30.md
docs/version0.35.md
docs/xoptionsfile.md
docs/xxensurehashed.md

https://github.com/eclipse-openj9/openj9-docs/issues/989
Updated the related topics with this addition to the default options.

-XX:+EnsureHashed:java/lang/Class,java/lang/Thread added to the default options list

---

docs/openj9_support.md

Issue https://github.com/eclipse-openj9/openj9/issues/16021

Update AIX xlc compiler level to 16.1.0.11

---

docs/xxensurehashed.md

https://github.com/eclipse-openj9/openj9-docs/issues/1012
Updated existing content for clarity

Updated existing content for clarity

---

docs/xdump.md

Closes https://github.com/eclipse-openj9/openj9-docs/issues/970
Updated the Xdump options topic with the defaults details

Update Xdump options topic

---

docs/version0.36.md
docs/xaot.md
docs/xjit.md
docs/xxmergecompileroptions.md
mkdocs.yml

Added a new topic for the -XX:[+|-]MergeCompilerOptions option and updated the related topics
Closes https://github.com/eclipse-openj9/openj9-docs/issues/1015

Document new -XX:[+|-]MergeCompilerOptions

---

JenkinsFile_build_doc.groovy

Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1849
Tested via https://openj9-jenkins.osuosl.org/view/Website-Doc/job/Build-Doc-Push_to_Eclipse/25
The docs directory is added to https://github.com/eclipse-openj9/openj9-website-publish

Publish release docs to github.com/eclipse-openj9/openj9-website-publish

---

docs/jitserver.md

Signed-off-by: Alexey Khrabrov <khrabrov@cs.toronto.edu>

Add a link to JITServer research paper in JITServer documentation

---

docs/openj9_support.md

https://github.com/eclipse-openj9/openj9-docs/issues/1044
Incorporated the feedback

Improvement to RHEL 6 support statement

---

buildenv/Dockerfile
buildenv/requirements.txt

https://github.com/eclipse-openj9/openj9-docs/issues/914
Updated Dockerfile and Requirements file.

Update Docker files for latest MkDocs levels

---

JenkinsFile_build_doc.groovy

Update the python path in the JenkinsFile_build_doc.groovy build script to match what's in the updated eclipseopenj9/openj9-docs:latest Docker agent
https://github.com/eclipse-openj9/openj9-docs/issues/914
Signed-off-by: Esther <doveye@uk.ibm.com>

Update the JenkinsFile_build_doc.groovy build script

---

.github/ISSUE_TEMPLATE/new-documentation-change.md
docs/cmdline_migration.md
docs/openj9_signals.md
docs/shrc.md
docs/version0.38.md

See https://github.com/eclipse-openj9/openj9-docs/pull/1080/files#r1164515536.

Correct several references to -XX: options

---

docs/criusupport.md
docs/dorgeclipseopenj9criuimmutableenvvars.md
docs/version0.38.md
docs/xrsonrestoresynconrestore.md
docs/xshareclassesdisableonrestore.md
docs/xxcheckpointgcthread.md
docs/xxcriurestorenonportablemode.md
docs/xxenablecriusupport.md
docs/xxignoreunrecognizedrestoreoptions.md
mkdocs.yml

https://github.com/eclipse-openj9/openj9-docs/issues/1053
Added content related to CRIU support
Closes #1053

CRIU Support Documentation

---

docs/openj9_support.md

Closes https://github.com/eclipse-openj9/openj9-docs/issues/1151

Mac 13 is a supported platform

---

docs/api/jdk8/platform/cuda/com/ibm/cuda/class-use/CudaDevice.CacheConfig.html
docs/api/jdk8/platform/cuda/com/ibm/cuda/class-use/CudaDevice.SharedMemConfig.html
docs/api/jdk8/platform/cuda/com/ibm/cuda/class-use/CudaException.html
docs/api/jdk8/platform/cuda/com/ibm/cuda/package-summary.html
docs/api/jdk8/platform/cuda/com/ibm/cuda/package-tree.html
docs/api/jdk8/platform/cuda/overview-tree.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/class-use/CorruptDataException.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/class-use/DataUnavailable.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/class-use/ImagePointer.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/class-use/JavaObject.html
docs/api/jdk8/platform/sharedclasses/com/ibm/oti/shared/class-use/SharedClassFilter.html

Using https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/675
Doc created by
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_linux_Personal/453/

Update jdk8 javadoc for 0.41

---

docs/version0.41.md
mkdocs.yml

Cherry pick the following for 0.41
https://github.com/eclipse-openj9/openj9-docs/pull/1209
https://github.com/eclipse-openj9/openj9-docs/pull/1210

(0.41) Add support for threadAllocatedBytes MXBean API

---

docs/shrc.md
docs/version0.41.md

https://github.com/eclipse-openj9/openj9-docs/issues/1212
Added information to the Introduction to class data sharing topic and What's new in version 0.41.0 topic.
Closes #1212

Ignore "allow" and "disallow" in java.security.manager

---

docs/shrc.md
docs/version0.41.md

https://github.com/eclipse-openj9/openj9-docs/issues/1212
Added information to the What's new in version 0.41.0 topic. Incorporated the feedback.
Cherry pick https://github.com/eclipse-openj9/openj9-docs/pull/1216 for 0.41

(0.41) Ignore "allow" and "disallow" set in java.security.manager system property

---

docs/api/jdk8/platform/cuda/com/ibm/cuda/class-use/CudaDevice.CacheConfig.html
docs/api/jdk8/platform/cuda/com/ibm/cuda/class-use/CudaDevice.SharedMemConfig.html
docs/api/jdk8/platform/cuda/com/ibm/cuda/class-use/CudaException.html
docs/api/jdk8/platform/cuda/com/ibm/cuda/package-tree.html
docs/api/jdk8/platform/cuda/overview-tree.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/class-use/CorruptDataException.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/class-use/ImagePointer.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/class-use/JavaObject.html

Built via
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Javadoc/170/

Update jdk8 api docs for 0.43

---

buildenv/requirements.txt

PyYaml upgrade to match the Python upgrade

---

docs/version0.43.md
docs/xxcpuloadcompatibility.md
mkdocs.yml

https://github.com/eclipse-openj9/openj9-docs/issues/1232
Created a new topic for -XX:[+/-]CpuLoadCompatibility. Updated the What's new in version 0.43.0 and mkdocs.yml file
Closes #1232

Documentation for -XX:[+/-]CpuLoadCompatibility

---

docs/criusupport.md

https://github.com/eclipse-openj9/openj9-docs/issues/1249
Added the new crypto services for CRIUSec provider.
Closes #1249

Add new crypto services for CRIUSec provider

---

docs/version0.44.md

Updated What's new in version 0.44.0

---

docs/version0.46.md

https://github.com/eclipse-openj9/openj9-docs/issues/1352
Updated the What's new in version 0.46.0 to emphasise the change in behavior
Closes #1352

Description changed for the HCR related update

---

docs/version0.46.md
docs/xtgc.md

https://github.com/eclipse-openj9/openj9-docs/issues/1296
Added information about the allocation parameter. Updated the What's new topic.
Closes #1296

Document -Xtgc:allocation

---

docs/version0.46.md
docs/xdynamicheapadjustment.md
mkdocs.yml

https://github.com/eclipse-openj9/openj9-docs/issues/1375
New option -XdynamicHeapAdjustment added. Related topics updated.
Closes #1375

CRIU: Heap Resizing on restore

---

docs/version0.46.1.md
mkdocs.yml

Created a draft What's new topic for 0.46.1

Release 0.46.1 What's new topic

---

docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/CorruptData.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/ImageAddressSpace.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/ImageModule.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/ImagePointer.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/ImageProcess.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/ImageSection.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/ImageStackFrame.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/ImageThread.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/class-use/CorruptDataException.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/class-use/DataUnavailable.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/JavaClassLoader.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/JavaHeap.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/JavaLocation.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/JavaMember.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/JavaMethod.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/JavaMonitor.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/JavaRuntime.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/JavaRuntimeMemoryCategory.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/JavaThread.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/JavaVMOption.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/runtime/ManagedRuntime.html
docs/api/jdk8/platform/dtfj/index-all.html

Doc created via
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Javadoc/227/

Update jdk8 javadoc for 0.48

---

docs/xxmergecompileroptions.md

https://github.com/eclipse-openj9/openj9-docs/pull/1392
Updated the topic for clarity.
Closes #1392

Updated the documentation for -XX:+MergeCompilerOptions

---

docs/version0.10.md
docs/xxexitonoutofmemoryerror.md

Option and file name corrected.

File name correction

---

docs/xxactiveprocessorcount.md
docs/xxadaptivegcthreading.md
docs/xxalwayspretouch.md
docs/xxcheckpointgcthread.md
docs/xxclassrelationshipverifier.md
docs/xxcodecachetotalmaxrampercentage.md
docs/xxcompactstrings.md
docs/xxcompatibility.md
docs/xxconcgcthreads.md
docs/xxcontinuationcache.md
docs/xxcpuloadcompatibility.md
docs/xxcriurestorenonportablemode.md
docs/xxcriusecprovider.md
docs/xxdiagnosesynconvaluebasedclasses.md
docs/xxenablecriusupport.md
mkdocs.yml

https://github.com/eclipse-openj9/openj9-docs/issues/1224
Incorporating customer requirement for relevant release information when the options were added. This will be done in parts.

Miscellaneous changes - Enhancement

---

docs/xloa.md
mkdocs.yml

https://github.com/eclipse-openj9/openj9-docs/issues/1424
To resolve the duplicate entries issue in the TOC and the tiny topic issue, combined multiple related topics into 1 topic.

TOC correction and Tiny topic merging

---

docs/openj9_support.md

Supported environment changes updated with support for macOS 15. Minor change

Update Supported environments topic

---

docs/shrc.md

https://github.com/eclipse-openj9/openj9-docs/issues/1492
Added information regarding -XX:Shareorphans option. Minor edits.
Closes #1492

Update SCC support for Custom class loader

---

mkdocs.yml

This change was not saved in the earlier commit.

Miscellaneous change

---

docs/xtrace.md

Changed reference to 0.50.0 release

Miscellaneous change - 0.51.0 release

---

docs/version0.51.md

https://github.com/eclipse-openj9/openj9-docs/issues/1520
Added content to the What's new topic.
Closes #1520

System property initialization changes

---

docs/tool_traceformat.md
docs/xxconcgcthreads.md
docs/xxenabledynamicagentloading.md
docs/xxensurehashed.md
docs/xxexitonoutofmemoryerror.md
docs/xxgloballockreservation.md
docs/xxhandlesigabrt.md
docs/xxhandlesigusr2.md
docs/xxheapdumponoutofmemoryerror.md
docs/xxheapdumppath.md
docs/xxidletuningcompactonidle.md
docs/xxidletuninggconidle.md

https://github.com/eclipse-openj9/openj9-docs/issues/1224
Incorporating customer requirement for relevant release information when the options were added. This will be done in parts. A general feedback related to formatting is also incorporated.

Miscellaneous changes - General enhancements

---

docs/xdump.md

https://github.com/eclipse-openj9/openj9-docs/issues/1538
Added the file path for the new version.
Closes #1538

Add new Dynatrace original_core_pattern path

---

docs/djavasecuritypropertieslist.md
docs/version0.55.md
mkdocs.yml

https://github.com/eclipse-openj9/openj9-docs/issues/1573
Created a new topic for the new system property. Updated the What's new topic and the mkdocs.yml file.
Closes #1573

Support a list of java.security property files in semeru JDKs

---

docs/version0.55.md

https://github.com/eclipse-openj9/openj9-docs/issues/1581
Updated the What's new topic with the change.
Closes #1581

The format of the java.vm.version System property is modified

---

docs/version0.55.md

https://github.com/eclipse-openj9/openj9-docs/issues/1585
Updated the What's new topic.
Closes #1585

JDK25 AIX 17.1.3 Runtime requirement

---

docs/api/jdk8/jre/management/extension/com/ibm/lang/management/OperatingSystemMXBean.html
docs/api/jdk8/platform/cuda/com/ibm/cuda/class-use/CudaException.html
docs/api/jdk8/platform/cuda/com/ibm/cuda/package-tree.html
docs/api/jdk8/platform/cuda/overview-tree.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/class-use/CorruptDataException.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/class-use/DataUnavailable.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/image/class-use/ImagePointer.html
docs/api/jdk8/platform/dtfj/com/ibm/dtfj/java/class-use/JavaObject.html
docs/api/jdk8/platform/sharedclasses/com/ibm/oti/shared/class-use/SharedClassFilter.html

Created from https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Javadoc/283

Update jdk8 api doc for 0.56

---

docs/xxidletuningminfreeheaponidle.md
docs/xxidletuningminidlewaittime.md

https://github.com/eclipse-openj9/openj9-docs/issues/1601
Added macOS and z/OS to these options topics as well.
Closes #1601

-XX:IdleTuningMinIdleWaitTime, -XX:IdleTuningMinFreeHeapOnIdle mac, zos
