eclipse-openj9/openj9-docs

NOTICE.md
The Notices file needs to state that the 3rd party
tools (Mkdocs, material and pygment) are not
redistributed.
Closes: #6
=> Update to notices file

docs/index.md, docs/openj9_support.md, docs/version0.9.md, docs/xscmx.md, mkdocs.yml
Add the agreed support statement from issue
https://github.com/eclipse/openj9-website/issues/79
Add release plan information for 0.9.0 and
update 0.8 to indicate 0.8.0.
Restructure index.md for readability and fix
a markdown markup issue in xscmx.md.
=> Addition of support and release information

docs/xxidletuningcompactonidle.md, docs/xxidletuninggconidle.md, docs/xxidletuningminfreeheaponidle.md, docs/xxidletuningminidlewaittime.md
Update the -XX idletuning options to
indicate that they are now supported on
all Linux architectures.
Closes: #26
=> Add extended support for idle tuning

.github/ISSUE_TEMPLATE/documentation-enhancement.md, .github/ISSUE_TEMPLATE/documentation-error.md, .github/ISSUE_TEMPLATE/new-documentation-change.md
Issue templates should help us get the
information we need from OpenJ9 contributors
or from users who find problems with the
documentation.
=> Add issue templates

docs/openj9_support.md
Update the docs/openj9_support.md topic
to add a row for Win32 support on JDK8.
Closes: #29
=> Add Windows x86-32 support

docs/xxinitialrampercentage.md, docs/xxmaxrampercentage.md, mkdocs.yml
-XXMaxRAMPercentage=N and -XXInitialRAMPercentage=N
New in OpenJDK 10 w/Hotspot and recognized by
OpenJ9 in all JDKs for compatibility.
Closes: #25
=> Add two new -XX options to set heap as a %

docs/xxinitialrampercentage.md, docs/xxmaxrampercentage.md
Added a sentence to each topic to explain
that apps in a container use the available
container memory.
=> Add additional content for containers

Dockerfile
Compatibility problems with pip installing
and upgrading via different package managers.
Preventing pip upgrading from 8 to 10. Must
reinstate when a pip 10 package is available
via apt.
=> Update Dockerfile to prevent pip upgrade

docs/dcomibmtoolsattachenable.md, docs/tool_jdmpview.md, docs/xdump.md, docs/xmint.md, docs/xtrace.md, docs/xxusecontainersupport.md, docs/xxverboseverification.md
Mostly these are bad markdown syntax,
which caused the HTML to be rendered not
quite as intended.
One further change to -XX:UseContainerSupport
that came from a recent review with development.
=> Fix issues identified in a recent check

docs/xtrace.md
Parameters listed in two groups under Syntax:
"Configuring trace" and "Controlling tracepoint activation"
and all parameters described in alphabetical order in Parameters section
Fixes #57 (see also https://github.ibm.com/runtimes/idteam/issues/77)
=> Refactor -Xtrace topic to avoid formatting problems

docs/openj9_support.md
GA now August. Updated table.
Also added the note back on that says
this release is expected.
=> Update date for 0.9.0 release

docs/xtrace.md
JSOR and JVerbs are available only in the
IBM SDK docs and should not be mentioned
here.
=> Remove RDMA components from trace topic

docs/openj9_support.md
From the mailing list:
---
Now that the 0.9.0 release is complete, it’s time to think about the schedule for future releases.
With OpenJDK’s new 6 month release cycle, new Java versions are released every 6 months.  With
JDK11’s September release fast approaching and followed closely after by the October JDK8 quarterly
update, there’s a lot of work to do!
What does this OpenJDK release landscape look like?
1) New versions of Java are released every 6 months: March and Sept.
2) Regular updates to existing releases happen quarterly: Jan, April, July & Oct.
What does OpenJ9 need to do?
OpenJ9 needs to at a minimum align with the quarterly updates to ensure critical fixes (including
security patches) are available in OpenJDK with OpenJ9 builds as soon as possible after the changes
appear in …
=> Update to include the 6 release/year policy

docs/xxmaxdirectmemorysize.md
Default is ~85% of max heap size (previously, doc said a limit was not set).
https://github.com/eclipse/openj9-docs/issues/67
[skip ci]
=> Correct the doc about default DirectByteBuffer memory limit

docs/env_var.md
Some instances of lower case `true` and `false`
when they should be upper case. Some missing
<values> from Java dump and heap dump ENVARs.
=> Fix for ENVVAR values for accuracy and consistency

docs/xshareclasses.md
A previous JDK 9 change to the cache size has now been backported to JDK 8, so there is no longer a need to document two separate sizes - remove old JDK 8 info and the icons that distinguished between the two releases.
https://github.com/eclipse/openj9-docs/issues/80
[skip ci]
Closes: 80
=> Change default shared class cache size info

docs/dump_javadump.md
Includes sections to cover all the different
parts that make up a Java dump file, with explanations
for the data. Makes use of a very recent javacore
that includes the new cgroup information for
https://github.com/eclipse/openj9/issues/1932
=> Add detail to initial Java dump topic

docs/xgcsplitheap.md
Fix minor typo on https://www.eclipse.org/openj9/docs/xgcsplitheap/ page
Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>
=> Fix typo: `porocess` -> `process`

CONTRIBUTING.md, docs/index.md, docs/openj9_defaults.md, docs/openj9_directories.md, docs/xlp.md, docs/xoptionsfile.md
OpenJDK 10 supersedes OpenJDK9, which is no longer
supported by OpenJ9. Changes to the docs required:
- replace any "9 and later" icons with "10 and later".
- replace any mentions of OpenJDK9 with OpenJDK10
where appropriate.
- remove links to OpenJDK9 downloads.
=> Remove references to unsupported OpenJDK9 release

docs/openj9_support.md, docs/version0.10.md, mkdocs.yml
Content going in to 0.10.0, with
support statements around OpenJDK8
vs OpenJDK11 builds.
=> What's new topic for v0.10.0

docs/index.md, docs/introduction.md, docs/version0.10.md, mkdocs.yml
Make the first topic more of an "about" topic
to position OpenJ9, what it is, how we present
information about Java versions, what we support
and where to find more information.
Move the task-oriented sections to a new topic that
we can build out as more content is written to support
configuration and tuning.
=> Separate "about this documentation" from user tasks

docs/xceehdlr.md, docs/xgcpolicy.md, docs/xscminaot.md, docs/xtrace.md
https://www.eclipse.org/openj9/docs/xceehdlr/ - last link ends in a "
Anchors:
- "metronome" link in https://www.eclipse.org/openj9/docs/xgcpolicy/ - the id is actually "metronome-aix-linux-only"
- "optavdpause" in same topic - should be "optavgpause"
- "default-behavior" in https://www.eclipse.org/openj9/docs/xscminaot/#default-behavior - there is no such section - remove
- All the links in the table under "Controlling tracepoint activation" in https://www.eclipse.org/openj9/docs/xtrace/ -  all need "-tracepoint" appended. In the same topic, the "options" link in the "Tracepoint activation" section - think the entire para might be superfluous - removed, after modifying the former one a bit. Also fixed a couple of typos
[skip ci]
=> Fix some broken links in the docs:

docs/version0.10.md
Now that builds are showing on the Adopt website
we need to udpate text and the link in our
0.10.0 release topic.
=> Update What's new - OpenJDK11 available at Adopt

docs/cmdline_migration.md, docs/xxinitialheapsize.md, docs/xxthreadstacksize.md, mkdocs.yml
Amplify explanation of -XX:+UseNUMA/-Xnuma:none option.
Re Slack comment from Ashutosh Mehra
Add -XX:InitialHeapSize, -XX:MaxHeapSize, and -XX:ThreadStackSize
aliases (and new option topics).
Resolves #96
=> Updates to migration topic for -XX:+UseNUMA and new aliases

docs/xxusecontainersupport.md
When running in a container environment the JVM increases
the maximum Java heap size by default. This change is
implemented by making -XX:+UseContainerSupport the
default.
Closes: #106
=> Change in default behavior for container awareness

docs/xshareclasses.md
See issue #103: https://github.com/eclipse/openj9-docs/issues/103
- New suboptions are bootClassesOnly and fatal.
- The default dir has changed from a temp dir to the user's home dir, on non-Windows platforms only, and only if groupAccess is not also specified.
[skip ci]
=> Add doc for new shared classes suboptions and default dir changes

docs/openj9_support.md, docs/version0.11.md, mkdocs.yml
New topic to describe whats in the 0.11.0 release.
Update to the support topic to include macOS
and changes to the OpenJ9 version table.
=> Add release notes and support information 0.11.0

docs/xcodecachetotal.md
Before it was possible to increase the size.
Changes added to OpenJ9 to allow decreasing the size.
Modifications made to the xcodecachetotal topic to
support this.
Also included the default sizes for 32/64-bit.
Closes: #138
Closes: #137
=> Add info for decreasing the total codecache size

docs/openj9_support.md
It had incorrectly said "yes" only for JDK12 which won't ship until
March.  Update the "No" for JDK8 and JDK11 to say "Yes" based on the
statements by RedHat that they will step forward as the stewards of
JDK8 and by others to indicate they will help with backports.
I've left the `(*2)` note on both of those "Yes"s though.
Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>
=> Correct 0.12.0 release line to say yes for 8 & 11

docs/version0.12.md, mkdocs.yml
To help users understand which features for 0.12.0
are already in the OpenJ9 code, we are introducing
draft release notes. This will be useful for users
who have picked up the last release from Adopt
(what is not in their build), but also useful for
users who pick up our planned milestone builds.
=> Add draft release notes

docs/version0.12.md
See issue: https://github.com/eclipse/openj9-docs/issues/110
Update What's New topic
[skip ci]
=> Doc updates for "Enable bootstrap class sharing by default jdk11"

JenkinsFile_build_container.groovy, JenkinsFile_build_doc.groovy
- Simplifies the process to test the PR containers
- No longer need to store/download from Jenkins
- Tag container based on PR ID
=> Upload PR containers to Docker Hub too

docs/introduction.md, docs/version0.12.md
OpenSSL support is now implemented for
OpenJDK 11. The same options and settings apply.
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/73
=> Update OpenSSL support to include OpenJDK11

docs/xenableexcessivegc.md, docs/xgc.md
-Xenableexcessivegc has the wrong default set.
Change it to enabled by default.
-Xgc:concurrentScavenge for Linux on Z, z/VM 7.1
hypervisor support now available.
=> Fix bugs and apply changes to -X options

docs/shrc.md, docs/version0.12.md, docs/xshareclasses.md
macOS recently added. See https://github.com/eclipse/openj9-docs/issues/149
[skip ci]
=> Doc changes: bootstrap class sharing enabled by default on all platforms

docs/tool_jdmpview.md, docs/version0.12.md, docs/xshareclasses.md
Add new section to What's New for 0.12.0, modify xshareclasses (cacheDirPerm section).
Also tweaked some markdown syntax in tool_jdmpview.
https://github.com/eclipse/openj9-docs/issues/178
[skip ci]
=> Doc updates for changes to default shared classes cache dir permissions

docs/introduction.md, docs/version0.12.md, docs/xxidletuningcompactonidle.md, docs/xxidletuninggconidle.md, docs/xxidletuningminfreeheaponidle.md, docs/xxidletuningminidlewaittime.md
GC on idle and compact on idle are now enabled
by default when OpenJ9 detects that it is running
in a container and the VM enters an idle state.
Topics udpated to introduce the new behaviour.
Closes: #112
=> Idle-tuning is enabled by default in 0.12.0

docs/shrc.md, docs/version0.12.md
Comment out section in What's New for 0.12.0, comment out section about enabling in modify shrc.md, and replace with old content about setting -Xshareclasses.
https://github.com/eclipse/openj9-docs/issues/187
[skip ci]
=> Doc updates for reverting shared classes enabled by default

CONTRIBUTING.md, README.md
A new staging service is now available that can
host multiple pull requests. Update the
contribution guidelines with the new repository
and URL for previewing drafts.
Draft doc is now hosted at the ghpages branch
of the repo, with the last release published
at the Eclipse site. Update the README to reflect
this.
Partially completes work for #176
=> Update for new staging service and draft site

docs/legal.md, docs/openj9_support.md, docs/version0.11.md, docs/version0.12.md
Updates to the what's new ahead of the 0.12.0
release to remove references to the release being
in progress. Update the support page to include
the macOS build system for 8 and remove the note
from 0.12.0 release to say it is in plan.
Late change to include RSA algorithm support added.
Pointed the 11 and 12 release topics at the
Adopt archive for macOS builds.
=> Finalise 0.12.0 release topics

docs/version0.12.md
Following the identification of issue
https://github.com/eclipse/openj9/issues/4530,
updated the content to warn users that
the Digest algorithm might cause a problem
with this release.
=> Add warning to version 0.12.0 topic

docs/tool_jps.md, docs/tool_migration.md, docs/version0.13.md
https://github.com/eclipse/openj9-docs/issues/210
Removed "compliance" for clarity - slight rewrites
[skip ci]
=> Tweak doc updates for jps tool_jps.md

docs/xxusecontainersupport.md
As title, just to fix an obvious typo.
Signed-off-by: Joseph Zhang <zaoxing.zhang@gmail.com>
=> Correct UseContainerSupport Option in document examples

docs/dump_javadump.md
The cgroup information in javacore is updated to have new tag
`3CICGRPINFO` for cgroup subsystems metrics. Earlier these
are having tag `2CICGRPINFO` (at the time of writing the doc).
The spacing is also adjusted to represent the current output
of the javacore.
Signed-off-by: bharathappali <bharath.appali@gmail.com>
=> Updating the doc with new tag and spacing in javacore.

docs/tool_jps.md, docs/tool_migration.md, docs/version0.13.md
The JPS work involved adding launcher code to the
extensions repository. The only branch that will get
created in extensions is on JDK 12, so this content
must be marked as applicable only to JDK 12.
Icon markers added.
=> Update JPS tool content to add icons for JDK 12

docs/gc.md, docs/xgc.md
Update gc.md: "Software-based support"
and xgc.md: concurrentScavenge
Resolves #134
=> Extend platform support for software-based pauseless GC

docs/index.md, docs/introduction.md, docs/openj9_support.md
Update support table and add sections for
OpenJDK 12 supported platforms and build system.
=> Updates to support topic for 0.13.0

docs/version0.13.md
Just spotted that we don't have an entry for extended pauseless GC
on Linux on POWER LE and AIX. Added.
=> Add missing whats new section

docs/adoptopenjdk.md, docs/index.md, docs/openj9_newuser.md, mkdocs.yml
For users who obtain binaries from Adopt, they need to be aware of: 
- platform support (link people to Adopts platform support matrix, which is slightly different from OpenJ9)
- Add the pre-reqs (1. OpenSSL no longer bundled on OpenJDK 12, so if they
need it they must install it locally. 2. On OpenJDK8 you need a fontconfig package to fix
a gap between Oracle licensed fonts and those used at Adopt.)
=> Add new AdoptOpenJDK topic

docs/djdknativecbc.md, docs/djdknativecrypto.md, docs/djdknativedigest.md, docs/djdknativegcm.md, docs/djdknativersa.md, docs/introduction.md, docs/version0.13.md
JDK 12 only
OpenSSL 1.0.2 is available on all platforms for Digest, CBC, GCM, and RSA.
On Linux and AIX you need to have it in your system path. For other
platforms the Adopt builds will bundle the 1.1.X library.
Digest re-enabled for 1.1.x
Closes: #188
=> Add support for OpenSSL 1.0.2

docs/version0.12.1.md
The link to the OpenJ9 release notes is missing
a ".". Reported in https://github.com/eclipse/openj9-website/issues/158.
=> Fix link in version 0.12.1 release topic

docs/cmdline_migration.md, docs/openj9_newuser.md, docs/version0.14.md, docs/xxignoreunrecognizedxxcolonoptions.md, mkdocs.yml
- Created new topic
- Updated content in https://eclipse.github.io/openj9-docs/openj9_newuser/ and https://eclipse.github.io/openj9-docs/xx_jvm_commands/, which talked about unrecognized options being ignored
- Created version0.14.md release notes topic, as this is the first update for the 0.14.0 release
- Also added -XX:IgnoreUnrecognizedVMOptions to https://eclipse.github.io/openj9-docs/cmdline_migration/, as it wasn't there but it's a HotSpot compatibility option, so probably should be
[skip ci]
=> Add/modify docs for new -XX:IgnoreUnrecognizedXXColonOptions option

docs/version0.14.md, docs/xgc.md
Support now extended to Linux on POWER BE architectures.
Updated the release topic for 0.14.0 and the xgc.md topic.
See https://github.com/eclipse/openj9/issues/5023
=> New support for ConcurrentScavenge GC mode

docs/xdump.md
This patch fixes typo in xdump docs
Resolves #238
[ci skip]
Signed-off-by: Zhongyi.li1 <zhongyi.li1@ibm.com>
=> Fixes typo in xdump docs

docs/djdknativecbc.md, docs/djdknativecrypto.md, docs/djdknativedigest.md, docs/djdknativegcm.md, docs/djdknativersa.md, docs/introduction.md, docs/version0.14.md
Add a section to the release topic, including warnings
about Adopt no longer bundling on Linux and AIX. Added
not about Digest re-enabled for Java 8 & 11.
Removed the Java 12 icons from all topics now that
support is available for 8 & 11, incuding the system properties.
=> Add support for OpenSSL 1.0.2 for Java 8 & 11

docs/openj9_support.md
Remove the marker that indicates 0.14.0 is in plan,
ready for GA.
All other parts of this doc seem fine.
=> Update support statement for 0.14.0

docs/xgcpolicy.md
Unless seccomp is set to unconfined, Docker blocks
JVM system calls that leverage NUMA characteristics.
Docs updated to recommend setting unconfined when starting
Docker if Balanced is used in a Docker container.
Closes: #227
=> Balanced GC requires seccomp=unconfined in Docker

docs/tool_jps.md, docs/tool_jstack.md, docs/tool_migration.md, docs/version0.14.md, mkdocs.yml
- New tools topic for jstack
- New section for jstack in the release topic
- Updated to Tools "Switching to OpenJ9" to describe differences to
HotSpot jstack
- Add jps to release topic for 8 & 11 (12 was in 0.13.0)
- Remove icons from jps content that specify Java 12 only.
Closes: #225
=> Add jstack (8,11,12) and update jps (8,11)

docs/version0.14.md
Update re change to shared classes cache in the 0.14
Whats new temporarily removed until changes made in
code (not until after Milestone 1).
=> Comment out "shared classes cache" in 0.14 Whats new

docs/version0.14.md
Restore work done in #250, which didn't make
milestone 1. Code now merged.
Closes: #248
=> Add information for shared cache generation no

docs/version0.14.md, docs/xxjitinlinewatches.md, mkdocs.yml
New option for turning on experimental JIT performance improvements
to support JVMTI watched fields.
- new topic
- update to release topic
- entry in Table of Contents
Closes: #252
=> Add option for JVMTI watched field performance

docs/tool_jps.md, mkdocs.yml
In 0.13.0, jps was only supported for OpenJDK12. It
is now supported for 8 & 11, but the icon is still
indicating that it applies to 12 only. Removed.
Also modified title slightly for consistency with jstack.
=> Remove Java 12 icon from jps topic

docs/gc.md, docs/xgc.md
Add documentation for software concurrent scavenge option -XXgc:softwareRangeCheckReadBarrier
update GC documentation with software CS information.
Signed-off-by: Nigel Yu <yunigel@ca.ibm.com>
=> Update documentation for software-based concurrent scavenge

docs/xdump.md
Correction to File Location option for JIT dumps on z/OS
Addition of note to explain how multiple suboptions must be separated by a
comma.
Closes: #256
Closes: #263
=> Fixes to the Xdump topic

docs/cmdline_migration.md
Add 3 Oracle options to the compatibility topic that are
recognized by OpenJ9.
=> Add missing options to the compatibility topic

docs/djdknativecbc.md, docs/djdknativecrypto.md, docs/djdknativedigest.md, docs/djdknativegcm.md, docs/djdknativersa.md, docs/introduction.md, docs/version0.14.2.md, mkdocs.yml
- Add OpenSSL 1.0.1 support
- Digest algorithm disabled by default
CLoses: #269
Closes: #260
=> Add changes for OpenJ9 0.14.2 release

docs/gc.md, docs/xgc.md
Now that we need a 0.14.2 release, this change
temporarily backed out until that release is
published.
=> Backout updates for 0.15.0 CS on Z

docs/version0.14.2.md
IcedTea-Web is being packaged only with OpenJDK8 (64-bit).
Fix statement.
=> Correct IcedTea-Web statement in release topic

docs/version0.15.md, docs/xxjitinlinewatches.md, mkdocs.yml
Changes to indicate that this was enabled by default in 0.15.0
were backed out due to 0.14.2. release. Now re-enabled.
Original PR: https://github.com/eclipse/openj9-docs/pull/267
=> Re-enable changes for XXJItInlineWatches

docs/gc.md, docs/xgc.md
Changes backed out due to 0.14.2 release, now
re-enabled to show support for concurrentScavenge mode
on IBM Z systems.
Original PR: https://github.com/eclipse/openj9-docs/pull/262
=> Re-enable changes for CS on z

docs/xgc.md
Add previously undocumented option.
Closes: #286
=> Add GC suboption: stdGlobalCompactToSatisyAllocate

docs/tool_jdmpview.md, docs/tool_jextract.md, docs/xrs.md, mkdocs.yml
See https://github.com/eclipse/openj9-docs/issues/268
[skip ci]
=> Add jextract information back into docs/tool_jdmpview.md

docs/version0.15.md, docs/xxjitinlinewatches.md
See https://github.com/eclipse/openj9-docs/issues/304
[skip ci]
=> Add z/OS and zLinux to JITInlineWatches doc

docs/adoptopenjdk.md
The "Java 12" tag was correct for the 0.13 release of Java 12, which proceeded
a release for all platforms. When 0.14 was released, the tag should have been
removed.
Closes: #293
=> Fix incorrect version label for OpenSSL pre-req

docs/djdknativecrypto.md, docs/djdknativedigest.md, docs/introduction.md, docs/version0.15.md
Digest was disabled in 0.14.2, which applied only
to Java 8 & 11. Digest algorithm is now turned off
in Java 12 for the same reason.
Closes: #294
=> Digest algorithm disabled in Java 12

docs/version0.15.md, docs/xxidletuningcompactonidle.md, docs/xxidletuninggconidle.md, docs/xxidletuningminfreeheaponidle.md, docs/xxidletuningminidlewaittime.md
Added dependency to XX:IdleTuningCompactOnIdle and
deprecated XX:IdleTuningCompactOnIdle. Also documented
added heuristics in version changelogs.
Fixes #277 
Signed-off-by: Shishir Halaharvi <shishir.neo95@gmail.com>
=> Deprecate XX:IdleTuningCompactOnIdle

docs/diag_overview.md, mkdocs.yml
The Diagnostics section is being expanded to cover all
data, tools, and interfaces supported by OpenJ9. This
requires a re-org of the current structure and an update
to the overview topic (renamed from Tools and data).
This is part of a larger piece of work, broken down into
incremental steps.
=> Updated Diag overview to support new structure

docs/introduction.md
If translations from English are not required,
tell users how to exclude the translated property
files, which reduces the size of the image.
Closes: #308
=> Include tip for using jlink

docs/version0.15.md, docs/xshareclasses.md
New -Xshareclasses suboptions to control whether timestamps
of zip or jar files are checked every time a class is loaded
or only on the first load (default).
Closes: #322
=> Change in shared classes behavior

docs/version0.16.md, docs/xxusegcstartuphints.md, mkdocs.yml
- Create the What's New topic for 0.16.0 and add this update.
- Update the -XX:UseGCStartupHints topic.
See https://github.com/eclipse/openj9-docs/issues/324
[skip ci]
=> Doc updates for UseGCStartupHints enabled by default

docs/version0.16.md
Update the 0.16 release notes in the user docs
See https://github.com/eclipse/openj9-docs/issues/345
[skip ci]
=> Doc updates for shared classes cache generation number update

docs/shrc.md, docs/version0.16.md, docs/xshareclasses.md
See https://github.com/eclipse/openj9-docs/issues/311
[skip ci]
=> Doc updates for bootstrap class sharing enabled by default

docs/djdknativecrypto.md, docs/djdknativedigest.md, docs/introduction.md
Change disabled restriction from applying to Java 8+ to Java 8, Java 11, and Java 12. When we have the archive doc package for 0.16.0, this text will need to change again as message digest will be enabled for all Java levels.
https://github.com/eclipse/openj9-docs/issues/353
[skip ci]
=> Doc update: Message digest is enabled on Java 13

JenkinsFile_build_doc.groovy
- Team has decided to support release branches instead
of tags since we could build multiple times.
- Code is more simple to support 1 option rather
than both.
=> Change from RELEASE_TAG to RELEASE_BRANCH for Doc builds

docs/djdknativecrypto.md, docs/djdknativedigest.md, docs/introduction.md, docs/version0.17.md, mkdocs.yml
Change 3 topics that mention message digest to remove the restriction where it was disabled for Java releases earlier than 13.
Also add a What's New section for this change.
https://github.com/eclipse/openj9-docs/issues/353
[skip ci]
=> Doc update: Message digest is re-enabled for all levels of Java

CONTRIBUTING.md, docs/adoptopenjdk.md, docs/djdknativechacha20.md, docs/djdknativecrypto.md, docs/index.md, docs/introduction.md, docs/openj9_support.md
OpenJDK 13 supersedes 12. Clean up docs to remove references to 12, including
icons.
=> Remove OpenJDK 12 references

docs/version0.17.md
0.16.0 was for JDK 13 only. Add pointer in release topic for
8 & 11 users to review the 0.16.0 changes as well as 0.17.0.
=> Add change information for JDK 8 & 11 users

docs/version0.17.md, docs/xshareclasses.md
For file systems that do not support disk space checking,
improves operations.
Closes: #357
=> Add new option -Xshareclasses:noPersistentDiskSpaceCheck

docs/xdump.md
Current platform restriction for Linux, macOS and Windows
only. However, user queried whether this should also state
z/OS. Confirmed by service.
=> Add z/OS as a supported platform for Xdump allocation events

docs/dump_javadump.md, docs/shrc_diag_util.md, docs/version0.17.md, docs/xshareclasses.md, mkdocs.yml
Add restriction and printTopLayerStats. Move printStats and printAllStats from IBM KC doc to OpenJ9.
https://github.com/eclipse/openj9-docs/issues/368
[skip ci]
=> Doc update: Shared classes cache layers 2

docs/version0.17.md
Added content to release notes. Docs incorrectly stated that this
was disabled by default already, when OpenJ9 used to enable by default.
Closes: #386
=> LUDCL caching now disabled by default.

docs/xdump.md
- dsn applies only to system dumps not CEEDUMPs
Closes: https://github.com/eclipse/openj9-website/issues/179
=> The -Xdump dsn option is not applicable to CEEDUMP

docs/xcheck.md
Extra back tick in VM section removed.
Closes: #390
=> Fix typo in xcheck command

docs/version0.17.md
LUDCL is disabled by default in this release due to an issue.
Adding the issue for further information.
Closes: #386
=> Update LUDCL item to include issue number

docs/adoptopenjdk.md, docs/dcomibmgpudisable.md, docs/dcomibmgpuenable.md, docs/dcomibmgpuverbose.md, docs/introduction.md, docs/xjit.md, mkdocs.yml
Now that CUDA enabled builds are available at AdoptOpenJDK, we should
have some information in OpenJ9 about how to take advantage of GPU
processing.
Minimal content included in this PR. Requires links to be added
Closes: #49 
Closes: #359
=> Bring in minimal content for GPU processing

docs/openj9_support.md, docs/version0.10.md, docs/version0.11.md, docs/version0.12.md, docs/version0.13.md, docs/version0.14.md, docs/version0.15.md, docs/version0.16.md, docs/version0.17.md, docs/version0.9.md
- make "v" before versions consistent
- fix broken link in 0.17.0
=> Tidy release notes

docs/xjit.md
Enforce can no longer guarantee that all lambdas are
sent to GPU for processing.
Closes: #397
=> Remove -Xjit:enableGPU=enforce

mkdocs.yml
The topic for -Dcom.ibm.lang.management.OperatingSystemMXBean.isCpuTime100ns was accidentally removed from the mkdocs.yml toc file.
Add it back for the 0.17 branch.
[skip ci]
=> Fix accidental removal of a system property topic

docs/tool_jdmpview.md, docs/tool_jextract.md, docs/version0.18.md, mkdocs.yml
Indicate that jextract is now available fopr all current
versions of OpenJDK running on macOS.
Update jextract and jdmpview topics, and add to a new version0.18 topic.
Closes #268
=> Update jextract on macOS

docs/gc.md, docs/version0.18.md, docs/xgc.md
Concurrent scavenge mode supported platforms must be updated to include macOS.
Following docs updated:
- Release notes v0.18
- GC platform list
- xgc options
Closes https://github.com/eclipse/openj9-docs/issues/433
Signed-off-by: Salman Rana <salman.rana@ibm.com>
=> Concurrent scavenge mode extended to macOS

docs/xcompilationthreads.md
Existing documentation specifies that the number of compilation threads
needs to be in the 1-4 interval. Starting with Java8 we have increased the
maximum number of compilation threads to 7.
Also, the behavior has changed in that the JVM will no longer fail if the
user specifies an invalid number of compilation threads; instead it will use
the default number according to its internal heuristics.
Closes #435
Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>
=> Correct documentation regarding XcompilationThreads option

docs/env_var.md, docs/introduction.md, docs/jit.md, docs/shrc_diag_util.md, docs/xgc.md
Minor updates as follows (inc. links to staged changes):
- Change link in introduction.md for GPU overview topic from SDK to VM ref ( https://eclipse.github.io/openj9-docs-staging/440/introduction/#exploiting-gpus )
- Correct platform support for concurrent scavenge mode of gencon GC policy ( https://eclipse.github.io/openj9-docs-staging/440/xgc/#concurrentscavenge )
- Correct format of long line of code in jit.md ( https://eclipse.github.io/openj9-docs-staging/440/jit/ )
- Correct codeblock content in env_var.md ( https://eclipse.github.io/openj9-docs-staging/440/env_var/#dump-agent-options)
=> Ad hoc fixes for 0.18.0

JenkinsFile_build_doc.groovy
- By default if the image exists on the
machine, the run will not update it.
Adding a pull will force an update
before running it.
=> Pull docker image before running

mkdocs.yml
Add tag for Google Analytics. The data is anonymized
by Mkdocs-Material, which is an Eclipse requirement for tracking data
on this project.
=> Add Google Analytics tracking code

docs/stylesheets/oj9.css, mkdocs.yml, theme/base.html, theme/partials/header.html
OpenJ9-docs build tools were updated earlier this week to move
up dependency levels. A new docker image was created and pushed
to the Docker hub Eclipse area. Draft docs are already built with
these levels, but required CSS changes.
The openj9-docs-0.17.0 branch was then updated to add in Google
Analytics tagging, but the HTML was rebuilt with the later build tool
levels and without the required CSS changes, causing the docs to render
incorrectly.
The same CSS changes are now applied to the branch. This has been
tested with a local build successfully.
=> Apply CSS changes for updated dependency levels

docs/interface_jvmti.md
Add `jint layer` information, which can be generated
with COM_IBM_ITERATE_SHARED_CACHES_VERSION_5.
Closes: #358
=> Update JVMTI topic for shared cache layer

docs/cmdline_migration.md, docs/version0.18.md, docs/xxconcgcthreads.md, docs/xxparallelcmsthreads.md, docs/xxparallelgcthreads.md, mkdocs.yml
Adding documentation to include the following new options:
-XX:ParallelCMSThreads
-XX:ConcGCThreads
-XX:ParallelGCThreads
Signed-off-by: AlenBadel <Alen.Badel@ibm.com>
=> Add support for Hotspot GC options

docs/introduction.md
We have seen problems running the [SortTest](https://github.com/eclipse/openj9/blob/master/test/functional/Java8andUp/src/org/openj9/test/gpu/SortTest.java) on Windows machines with older, less powerful GPUs. The resolution was to increase the `TDR` timeout as discussed in this addition.
Closes #478
=> Add note about using using the WDDM driver model for GPUs on Windows

docs/version0.15.md, docs/version0.18.md
Additional fixes are included for Java 8 & 11, resulting in
binaries at AdoptOpenJDK for v0.18.1. Explanation added to the
what's new topic.
=> Update what's new for v0.18.1 binaries

docs/dump_javadump.md
Fixes: https://github.com/eclipse/openj9-docs/issues/491
The line: `2SCLTEXTNSH            Number Startup Hint Entries               = 0` is missing from the `SHARED CLASSES subcomponent dump routine` section on https://www.eclipse.org/openj9/docs/dump_javadump/#shared-classes.
=> Add in missing Number Startup Hint Entries on javadump page

docs/cmdline_migration.md, docs/version0.19.md, docs/xxprintcodecache.md, mkdocs.yml
`-XX[+|-]PrintCodeCache` prints the code cache usage when the application exits.
Closes #499
Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>
=> New command line options: -XX[+|-]PrintCodeCache

docs/openj9_support.md
In openj9_support.md, extra sections added under both
'Platform support' and 'Build environments' for OpenJDK 14.
=> Update 'Supported environments' topic for OpenJDK 14

docs/openj9_support.md
Also fix the spelling of Centos -> CentOS
Fixes: https://github.com/eclipse/openj9-docs/issues/507
=> Fix support statement, Linux x86 builds on CentOS 6

docs/openj9_releases.md, mkdocs.yml
Page to introduce OpenJ9 releases and provide links to
the Eclipse project page and support lifecycle.
There will be a link to this page from the redesigned
OpenJ9 site (news page)
=> New top level releases page

docs/xdump.md
It was pointed out in OpenJ9 slack that the docs are not very clear about the differences between Xdump `throw` and `systhrow` events.
=> Clarify xdump throw vs systhrow

docs/gc.md
Comment out edited information in gc.md and add Balanced back in to 'Other policies' section
=> Remove Balanced GC double mapping info for 0.19.0

docs/openj9_support.md
CentOS 6 doesn't support ppc64le so OpenJ9 can't possibly support this.
Closes #522
=> CentOS 6 is not supported for plinux

docs/openj9_support.md
=> OpenJ9 uses gcc 7.5 to compile on Linux

docs/tool_jextract.md
Fixes https://github.com/eclipse/openj9-docs/issues/531
=> Remove obsolete jextract requirements

docs/version0.20.md, docs/xxexitonoutofmemoryerror.md
Fixes: https://github.com/eclipse/openj9-docs/issues/540
=> -XX:[+-] ExitOnOutOfMemoryError for systhrow only

docs/openj9_defaults.md, docs/xxoriginaljdk8heapsizecompatibilitymode.md
fix: https://github.com/eclipse/openj9-docs/issues/511
Signed-off-by: Lin Hu <linhu@ca.ibm.com>
=> The default value of `-Xmx` is changed in Java 8

docs/version0.20.md, docs/xxoriginaljdk8heapsizecompatibilitymode.md
- add missing what's new item that covers change to -Xmx default on Java 8
- slight mods to other entries for consistency
=> Add new -Xmx default to release notes

docs/version0.20.md
**Jcmd dump with default settings**
Jcmd Dump command now supports default settings when the dump request
doesn't have :file=name option which is similar with Java -Xdump default
settings.
closes: #538 
Signed-off-by: Jason Feng <fengj@ca.ibm.com>
=> Jcmd dump with default settings

docs/version0.20.md
Tidy wording for jcmd entry re default settings
(also fix broken link to xxexitonoutofmemoryerror.md)
See issue #538 and PR #545
=> Edit jcmd in "What's new"

docs/adoptopenjdk.md, docs/xoptionsfile.md
In the topic that describes the pre-built binaries, add a section
to point users to the location of our detailed build instructions for
developers who want to build their own binary.
Closes: https://github.com/eclipse/openj9-website/issues/155
=> Add information about where to find build your own instructions

docs/openj9_support.md, docs/version0.19.md, docs/version0.20.md, mkdocs.yml
Release notes topic:
New bullet and section for the AArch64 support in this release.
Supported environment topics:
Add AArch64 to the OpenJDK11 support table, and incude AArch64 build system information too.
Closes: #547
=> Add AArch64 limited support

docs/tool_jdmpview.md
Document the jdmpview options that are used to find native libraries
when looking at a core file on a different system from where it was
produced, or when the JVM that produced the core is no longer at the
original location.
Also remove references to XML files, which are obsolete and no longer
produced by jextract.
Closes #551
=> Document jdmpview native library location options

docs/tool_jdmpview.md
The path separator is a semi-colon (';') on Windows, and a colon (':') on other platforms.
=> Clarify reference to path separators

docs/openj9_support.md
Cherry pick #557 - Remove support for Windows 8.1, Server 2012, but not R2
and #558 - Linux on ARM 64-bit uses gcc 7.5
for the 0.20.0 branch.
=> Update the 0.20.0 branch support statement

docs/version0.21.md
Update What's New for 0.21 to include `NoClassDefFoundError` exception message update
Fixes: https://github.com/eclipse/openj9-docs/issues/563
Related: https://github.com/eclipse/openj9/pull/9588
=> Note update to NoClassDefFoundError exception message

docs/openj9_support.md
=> Linux on ARM 64-bit uses gcc 7.5

docs/xshareclasses.md
=> -Xshareclasses groupAccess should be used with cacheDir

docs/xaot.md
https://github.com/eclipse/openj9-docs/issues/569
Removed sentence about default behaviour of shared classes as there's already a link to the "Class data sharing" topic, which describes that. Instead, expanded on the info the user can get from that topic. This way, the user can still easily get the shared classes info but the -Xaot topic won't need to be updated (possibly getting missed again and providing incorrect info) when/if the default shared classes behaviour changes in the future.
=> Remove sentence about default behaviour of shared classes

CONTRIBUTING.md, docs/xtgc.md
1x "whitelist" in `CONTRIBUTING.md` : ("whitelisted users" --> "approved users")
0x "blacklist"
1x "master" in `xtgc.md` : ("master thread" --> "main thread")
4x "slave" in tool_jdmpview.md in output example *not* changed until code changes
NB references to "master" in following link path not considered at present:
`https://github.com/eclipse/openj9/blob/master/doc/release-notes/...`
See https://github.com/eclipse/openj9/issues/10071
=> Updates to docs re inclusive language

.gitignore, docs/version0.22.md, mkdocs.yml
- new topic with info about OpenJDK 15 planned binaries
- update mkdocs.yml for TOC
- add overdue .gitignore
=> Add release topic for 0.22.0

docs/openj9_support.md
- glibc minimum 2.12 only applies to x. others have a minimum 2.17
- update RHEL/CentOS 6 minimum to 6.10
- update RHEL/CentOS 7 minimum to 7.6
- remove RHEL 6 support for Z
- fix build environment for P, it was changed some time back
Fixes #613
=> Update JDK15 xlinux build env and update minimum support levels

docs/version0.22.md
`java.lang.System.mapLibraryNamepublic(libname)` returns a platform-specific string representing a native library with `.so` suffix at `JDK15+` `AIX`.
Signed-off-by: Jason Feng <fengj@ca.ibm.com>
=> AIX JDK15+ j.l.System. mapLibraryNamepublic() returns .so lib suffix

docs/xms.md, docs/xxinitialrampercentage.md, docs/xxusecontainersupport.md
- The `-XX:InitialRAMPercentage` option is ignored, when -Xms is
specified.
- The `-XX:MaxRAMPercentage` option is ignored, when -Xmx is specified.
Signed-off-by: Lin Hu <linhu@ca.ibm.com>
=> Improve the detail condition for container-related docs

docs/version0.22.md
It should be `java.lang.System.mapLibraryName`.
Signed-off-by: Jason Feng <fengj@ca.ibm.com>
=> Fix incorrect API name

docs/openj9_defaults.md, docs/xxusecontainersupport.md
- explain the default max heap size limit to 25GB.
- options to overwrite the limit.
Closes #626
Closes https://github.com/eclipse/openj9/issues/10200
=> The Default max heap size limit

docs/api-jdk11.md, docs/api/jdk11/search.js
The search.js script expects an iframe with a name of "classFrame" otherwise the search silently (to the user) fails.
=> Update the jdk 11 iframe to use a name which search.js expects

docs/openj9_support.md
Add AArch64 column to platform support table OpenJDK 15
=> Updates to openj9_support.md

docs/version0.23.md, docs/xxportablesharedcache.md
Introduced additional changes to the Portable Shared Cache feature (-XX:[+|-]PortableSharedCache) which eliminates the AOT portability issues of Compressed Reference OpenJ9 builds with heap sizes from 0GB to 28GB. Previously compressed reference JVMs with different heap sizes cannot share AOT compiled code with each other. When Portable Shared Cache is enabled (either via -XX:[+|-]PortableSharedCache or by default in containers), Compressed Reference OpenJ9 builds with heap size in the range of 0GB to 28GB will be able to share AOT complied code with each other. However there will be a slight steady-state throughput penalty of 1-2% when using this option now compared to before.
Signed-off-by: Harry Yu <harryyu1994@gmail.com>
=> Update documentation for PortableSharedCache

docs/tool_jextract.md, docs/version0.23.md
Build ID of jextract utility checked against SDK build ID in dump.
If they don't match, an exception is thrown. New option allows override.
Closes: #649
=> jextract checks build ids, change in behavior

jenkinsFile_cleanup_staging.groovy
Cleanup PRs from staging site which are no longer open.
- Get list of currently staged PRs.
- Query Github to determine Open/Closed/Merged.
- Remove Closed and Merged PRs.
- Push back to staging repo
=> Initial check-in of cleanup staging script

docs/xshareclasses.md
- Add (cache utility) to option
- Slight rewording of cache utility intro and fixing of references to VM acronym.
=> Option destroyAlllayers not classified as a cache utility

docs/gc.md
- Replace existing article with a new link to a more recent OpenJ9 blog post.
Closes: #677
=> Fix broken links to concurrent scavenge articles

docs/cmdline_migration.md, docs/interface_jvmti.md, docs/messages_intro.md, docs/version0.24.md, docs/xlog.md, docs/xsyslog.md, docs/xxlegacyxlogoption.md
- Further mods to help clarify relationship between -Xlog, -Xsyslog and the new -XX option
- For HotSpot customers, add to table about similar functioning options
- Add notes here and there for existing users about -Xlog superseded
- Some edits in the version topic for consistency etc.
=> Further updates to support changes to message logging

docs/allocator.md, docs/xcompressedrefs.md, docs/xms.md
- add to memory allocation topic
- link to -Xmx topic for large page guidance
- update -Xmx to add guidance for large pages
=> Add information about compressed refs and SOA/LOA

docs/gc.md, docs/xgc.md, docs/xgcpolicy.md
- Apply agreed terminology changes to all policies
- Make structure consistent across areas
- Move "when to use" information from xgcpolicy option to main topic
=> Align GC policy terminology and structure

docs/version0.24.md
- `abortonerror` provides diagnostic data for fatal JNI errors.
Closes: #693
=> Add new suboption for -Xcheck:jni

docs/gc.md, docs/gc_overview.md, mkdocs.yml
- Rename allocator.md topic to gc_overview.md
- Overview contains Allocator and top level Garbage Collection topics
- gc.md becomes the GC policies topic
- no new words, just moves.
=> GC section restructure

docs/openj9_support.md
Fixes https://github.com/eclipse/openj9-docs/issues/697
=> Java 15 builds Windows with VS2019

docs/openj9_support.md
JDK 17 is an LTS release, remove note reference to feature release.
=> Fix support table to remove incorrect note

docs/introduction.md
* code page conversion was never a supported use-case; mention array sorting instead
* GPU use is also supported on Linux aarch64; in fact they're supported on all little-endian architectures
Fixes #712.
=> Correct introduction to exploiting GPUs

docs/tool_jdmpview.md
* note that `jextract` can make more information available to `jdmpview`
* update sample `jdmpview` version banners
Fixes #714.
=> Expand note about information that may not be in core files

theme/partials/footer.html
The footer is included in multiple pages at differing depths in the tree, so absolute paths are required.
=> Use absolute paths in footer links

docs/index.md, docs/openj9_support.md, docs/version0.25.md, mkdocs.yml
version0.25.md : new page added
index.md : explanation of icons updated to later versions
openj9_support.md : updated for new version (OpenJDK 15 sections in 'Platform support' and 'Build environments' changed to OpenJDK 16, but all values need checking)
=> Initialise "What's New" etc. for 0.25.0

docs/version0.25.md
Explain which features apply/don't apply and whether they are implemented yet.
Add note about JEP 396, which might break user apps.
Also add note about general support for Java 8 & 11. No testing in this release and remove Windows compiler update that was copied through from 0.24.
Closes: #726
=> Add list of JDK 16 features that apply to OpenJ9

docs/introduction.md, docs/version0.25.md
* Hardware acceleration section with the use of `zlibNX`
* Release notes addition of the default `zlib` changes on AIX
Changes: eclipse/openj9#11624
Closes: #722 
Signed-off-by: Abdulrahman Alattas <rmnattas@gmail.com>
=> Add HW acceleration and AIX default zlib changes

docs/cmdline_migration.md, docs/introduction.md, docs/version0.25.md, docs/xxdiagnosesynconvaluebasedclasses.md
- JEP 390: Add -XX option to migration topic. Fix missing `<number>` and add table for options. Minor updates to release topic.
- Style changes for zlibNX updates.
=> Editorial changes to 0.25.0 updates

docs/version0.25.md
- broken link to compressed references section
- describe a single build that is capable of running compressed references and non-compressed references rather than introducing term "mixedrefs"
- minor changes for grammar etc.
=> Fix broken link and references to mixedref builds

docs/xconcurrentbackground.md
Documentation for `Xconcurrentbackground` default behaviour is not up-to-date, the default value 1 is on all platforms. Obsolete limitation on zLinux was removed some time back - https://github.com/eclipse/omr/pull/3617.
Signed-off-by: Salman Rana <salman.rana@ibm.com>
=> -Xconcurrentbackground default value correction

docs/version0.25.md
Fixes https://github.com/eclipse/openj9-docs/issues/748
=> -Xmx link wrong in What's new in version 0.25.0

docs/diag_overview.md, docs/gc.md
Adding links to the new Verbose GC log topic (vgclog.md) from:
- gc.md
- diag_overview.md
Signed-off-by: MelHopper <melanieh@uk.ibm.com>
=> adding links to the new verbose GC log topic

JenkinsFile_build_doc.groovy
We need to pull the base.html file from the material theme in order
to insert our staging/draft docs banner. It is not needed as a
permanent artifact in the repo, we can just bring it in at build time.
Signed-off-by: Sue-Chaplain <sue_chaplain@uk.ibm.com>
=> Fix staging and draft banner

JenkinsFile_build_container.groovy, JenkinsFile_build_doc.groovy
See [Eclipse Bugzilla 572408](https://bugs.eclipse.org/bugs/show_bug.cgi?id=572408)
cc @mbarbero
=> Update DockerHub namespace to eclipseopenj9

docs/gc_overview.md, docs/version0.26.md, docs/xgc.md, mkdocs.yml
Add the 3 `-Xgc` suboptions that control scan ordering for GC operations
that evacuate objects in the heap.
Add the change in behavior for `balanced` to use dynamic breadth first scan mode.
Closes: #703
Signed-off-by: Sue-Chaplain <sue_chaplain@uk.ibm.com>
=> Add scan ordering options and new default for balanced

docs/gc.md, docs/xgc.md, docs/xgcpolicy.md
- adds two -Xgc suboptions that trigger GCs related to class unloading activity.
Closes: #756
=> Add missing class unloading options

docs/gc_overview.md, docs/version0.26.md, docs/xgc.md
Scan ordering switched back to Breadth First due to underlying problems.
Closes: #768
=> Backout change for balanced GC policy

docs/diag_overview.md, docs/interface_dtfj.md, docs/tool_jdmpview.md, docs/tool_jextract.md, docs/version0.26.md
- Added info to the release topic about deprecating jextract
- Changed the references in the jextract topic to jpackcore, including a note about jextract deprecation
- Found and updated other references to jextract in the docs.
Closes: #767
=> Deprecate jextract, replace with jpackcore

docs/index.md
The IBM Knowledge Center is renamed to IBM Documentation.
=> Name change for IBM Knowledge Center

docs/xtrace.md
Date and timestamp tokens are incorrectly documented as %d% AND %t%.
Replace with %d and %t.
Closes: #773
=> Fix -Xtrace exception.output

docs/shrc.md, docs/xshareclasses.md
- new section on BCI support and sharing modified bytecode in the cache.
- a few minor updates to other shared classes sections.
=> Add content for BCI support in class data sharing

docs/vgclog_examples.md
A couple of broken anchors discovered in extended testing.
=> Fix anchor links in vgc log examples

docs/version0.27.md, docs/xgcmaxthreads.md, docs/xgcthreads.md, docs/xxadaptivegcthreading.md, docs/xxparallelgcmaxthreads.md, docs/xxparallelgcthreads.md, mkdocs.yml
With the introduction of Adaptive GC Threading optimization  (https://github.com/eclipse/openj9/pull/11999 & 
https://github.com/eclipse/omr/pull/5830), new options need to  documented and some of the existing options need to be updated for  clarification.
Discussion on the behaviour, naming and interaction with existing  options can be found at https://github.com/eclipse/openj9/issues/12119.
New options:
**XX:**
`-XX:[+-]AdaptiveGCThreading` to enable/disable the GC adaptive threading  optimization.
`-XX:ParallelGCMaxThreads=` Mapped to Xgcmaxthreads (see below)
**Xgc:**
`-Xgcmaxthreads` The max number of threads available to Adaptive Threading  (Similar to Xgcthreads, except it doesn’t set forced thread count flag)
Existing `Xgcthreads` & `XX:ParallelGCThreads=` option pages updated …
=> Adaptive GC Threading Documentation

docs/xalwaysclassgc.md, docs/xclassgc.md, docs/xcompactgc.md, docs/xconcurrentbackground.md, docs/xconcurrentlevel.md, docs/xconcurrentslack.md, docs/xconmeter.md, docs/xenableexcessivegc.md, docs/xenableexplicitgc.md, docs/xenablestringconstantgc.md, docs/xgc.md, docs/xgcpolicy.md, docs/xgcsplitheap.md, docs/xgcthreads.md, docs/xgcworkpackets.md, docs/xloa.md, docs/xloaminimum.md, docs/xmca.md, docs/xmine.md, docs/xminf.md, docs/xmint.md, docs/xmn.md, docs/xmo.md, docs/xmoi.md, docs/xms.md, docs/xsoftmx.md, docs/xsoftrefthreshold.md, docs/xtlhprefetch.md, mkdocs.yml
- Add clarity for GC options regarding which policies can and can't use them.
- Move a few metronome `-Xgc` options from `-Xgcpolicy` to their correct location.
- Some tidying up/editing improvements.
=> Improve mapping of GC policies to GC options

CONTRIBUTING.md, JenkinsFile_build_doc.groovy, buildenv/requirements.in, buildenv/requirements.txt, docs/api-conditionhandling.md, docs/api-cuda.md, docs/api-daa.md, docs/api-dtfj.md, docs/api-gpu.md, docs/api-jdk11.md, docs/api-jdk16.md, docs/api-jvm.md, docs/api-langmgmt.md, docs/api-shrc.md, mkdocs.yml
Includes updates to:
- Switch search off for the offline build . The material theme does not support search on local sites
- Correct the table layout in Supported environments which is broken by the material upgrade
- Use the `mkdocs-macros-plugin` to allow correct links  to offline api doc
- Fix relative urls to api docs due to path changes caused by use_directory_urls
- Explain how to reference non-Markdown files in the contributions guidelines
=> Updates for Material theme 7.1.4

docs/gc_overview.md, docs/version0.27.md, docs/xgc.md
Add the change in behavior for `balanced` to use a dynamic breadth-first scan ordering policy.
Closes: https://github.com/eclipse-openj9/openj9-docs/issues/703
Related to: https://github.com/eclipse-openj9/openj9/pull/12775
Signed-off-by: Jonathan Oommen <jon.oommen@gmail.com>
=> Add new default GC Scan Ordering for Balanced

docs/version0.27.md
AdaptiveGCThreading is enabled by default.
Issue https://github.com/eclipse-openj9/openj9-docs/issues/766
This updates https://github.com/eclipse-openj9/openj9-docs/pull/765
=> Update AdaptiveGCThreading release note

docs/version0.27.md, docs/xxgloballockreservation.md
version0.27.md is updated to reflect that global lock reservation is now
enabled by default on AIX and Linux on Power.
Similarly, xxgloballockreservation.md is also updated to reflect this.
Closes: #799
Signed-off-by: jimmyk <jimmyk@ca.ibm.com>
=> Document -XX:+GlobalLockReservation as new default

docs/xxenable3164interoperability.md, mkdocs.yml
This option enables 31/64-bit interop support for z/OS
=> Document -XX:Enable3164Interoperability

CONTRIBUTING.md, README.md, docs/index.md
For example, https://openj9.github.io/openj9-docs-staging/ should be https://eclipse-openj9.github.io/openj9-docs-staging/.
=> Update URLs to reflect switch to github organization 'eclipse-openj9'

docs/xmint.md
The format of the values listed should be a percentage (see https://github.com/eclipse-openj9/openj9-docs/issues/803)
=> Fix default -Xmint/-Xmaxt values

docs/version0.28.md, mkdocs.yml
Add the initial draft "Release note" topic for 0.28, ready for updates for each feature as it comes.
This release is to support JDK 17 (next LTS), so add content to mention that.
Also move one of the previous "Release note" topics into the "Earlier releases" section to avoid cluttering the table of contents.
=> Add the initial draft "Release note" topic for 0.28

README.md
The Jenkins server has moved to https://openj9-jenkins.osuosl.org/.
=> Update URLs for build status

docs/attachapi.md
Update AttachAPI Windows default temporary directory
Related to https://github.com/eclipse-openj9/openj9/issues/13571
closes https://github.com/eclipse-openj9/openj9-docs/issues/851
Signed-off-by: Jason Feng <fengj@ca.ibm.com>
=> Update AttachAPI Windows default temporary directory

docs/shrc.md, docs/shrc_diag_util.md, docs/xshareclasses.md
1. The z/OS default cache directory is /tmp/javasharedresources
2. Add message that the cache directory should not be set on NFS or
shared mount.
Closes #828
=> Change documentation on z/OS default cache directory

docs/cmdline_specifying.md, docs/dump_javadump.md, docs/version0.30.md
As [requested](https://github.com/eclipse-openj9/openj9/pull/13579#issuecomment-975461319).
Also, clean up:
* collapse multiple blank lines
* trim trailing whitespace
* expand tabs
=> Document ignored arguments section in java dumps

docs/version0.29.1.md, mkdocs.yml
Port of https://github.com/eclipse-openj9/openj9-docs/pull/868 for the 0.29.1 release branch.
=> (0.29.1) Add 0.29.1 release notes

docs/dump_systemdump.md
Fixes https://github.com/eclipse-openj9/openj9-docs/issues/874
Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>
=> Issue #874: Fix command separation

docs/xmn.md
https://github.com/eclipse-openj9/openj9/pull/12043 will add support for the options mentioned above, for the Balanced GC policy.
This PR contains the documentation changes required to reflect this new behaviour.
closes #834
Signed-off-by: Cedric Hansen <cedric.hansen@ibm.com>
=> Modify -Xmn/-Xmns/-Xmnx documentation for balanced GC changes

docs/version0.30.md, docs/xgc.md, docs/xmn.md, docs/xtgc.md
Cherry pick the commits from https://github.com/eclipse-openj9/openj9-docs/pull/838 https://github.com/eclipse-openj9/openj9-docs/pull/839 https://github.com/eclipse-openj9/openj9-docs/pull/841 https://github.com/eclipse-openj9/openj9-docs/pull/891 https://github.com/eclipse-openj9/openj9-docs/pull/892 for the 0.30 branch.
=> Update 0.30 branch with missing docs

docs/xjit.md
Added a note (after the Parameters table) that only the most recent -Xjit option takes effect.
=> https://github.com/eclipse-openj9/openj9-docs/issues/873

docs/openj9_support.md
Copy of the jdk17 lists since nothing has changed.
=> Add jdk18 to the supported environments

docs/tool_jcmd.md, docs/tool_jmap.md, docs/tool_jps.md, docs/tool_jstack.md, docs/tool_jstat.md
Added the Attach API related information to jmap, jstack, and jstat topics as it was missing.
=> https://github.com/eclipse-openj9/openj9-docs/issues/863

docs/version0.31.md, docs/xxmaxdirectmemorysize.md
Fixes https://github.com/eclipse-openj9/openj9-docs/issues/905
=> Adjust -XX:MaxDirectMemorySize defaults

docs/openj9_support.md
https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms
https://www.oracle.com/java/technologies/javase/products-doc-jdk17certconfig.html
https://www.oracle.com/java/technologies/javase/products-doc-jdk18certconfig.html
=> OpenJDK jdk17 is supported on OSX 10.14+, jdk18 on 10.15+

docs/cmdline_migration.md, docs/version0.32.md, docs/xxshowhiddenframes.md
https://github.com/eclipse-openj9/openj9-docs/issues/910
Updated the ShowHiddenFrames content to mention HotSpot for consistency. Added that this option doesn't affect the dump file. Added this option to the table in the Switching to OpenJ9 topic.
=> Update RAS documentation regarding Hidden frames

docs/configuring.md, docs/openj9_support.md, docs/version0.33.md, mkdocs.yml
Fixes https://github.com/eclipse-openj9/openj9-docs/issues/932
=> AIX 11.0.16 requires the 16.1 XL C++ Runtime

docs/openj9_support.md, docs/version0.33.md
Closes https://github.com/eclipse-openj9/openj9-docs/issues/938
=> jdk17+ Linux platforms use gcc 10.3 to compile

docs/xxparallelgcthreads.md
Closes https://github.com/eclipse-openj9/openj9-docs/issues/931
=> Minor doc issues

docs/cmdline_migration.md
https://github.com/eclipse-openj9/openj9-docs/issues/937
Added that -XX:+CompactStrings option must be specified (enabled) to make the option behave the same as it does in HotSpot.
=> Added -XX:+CompactStrings to Creating compatible behavior section

docs/xxmaxdirectmemorysize.md
https://github.com/eclipse-openj9/openj9-docs/issues/947
Updated the content as memory consumption from the native memory rather than the heap memory.
=> Updated Direct Byte Buffers native memory reference

docs/jitserver.md, docs/version0.33.md
https://github.com/eclipse-openj9/openj9-docs/issues/930
Updated the document to reflect the JITServer support for openssl 3.
=> Updated to reflect JITServer support for openssl 3

docs/allocation.md, docs/version0.30.md, docs/xgcpolicy.md, docs/xminf.md, docs/xmint.md
https://github.com/eclipse-openj9/openj9-docs/issues/835
-Xmint/-Xmaxt, -Xminf/-Xmaxf, and -Xgcpolicy topics modified to reflect the changes applicable for the balanced GC policy.
=> Modified -Xmint/-Xmaxt and -Xminf/-Xmaxf for balanced GC

docs/openj9_support.md, docs/version0.35.md
https://github.com/eclipse-openj9/openj9-docs/issues/981
Updated that the Windows jdk11 compilation now uses VS2019.
=> Updated Windows jdk11 compilation uses VS2019

docs/openj9_support.md
Update the macOS build platforms and compilers to reflect reality
Pull Request https://github.com/eclipse-openj9/openj9/pull/15433
=> Update macOS platform and compiler information

docs/dump_javadump.md, docs/version0.35.md, docs/xxshownativestacksymbols.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/977
-XX:[+|-]ShowNativeStackSymbols option added
Made changes to related topics
=> Document new options to control resolution of native stack symbols

docs/dump_javadump.md, docs/openj9_signals.md, docs/version0.35.md, docs/xdump.md
https://github.com/eclipse-openj9/openj9-docs/issues/978
Updated the dump events list with user2 event. Explained the behavior.
=> Document new -Xdump user2 event for the SIGUSR2 signal

docs/version0.35.md, docs/xdump.md, docs/xjit.md, docs/xxperftool.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/983
Added -XX:PerfTool option
Added -Xjit:perfTool option in the related topic
=> Document new standalone options for PerfTool

docs/openj9_support.md, docs/version0.35.md
Closes https://github.com/eclipse-openj9/openj9-docs/issues/1005
Updated the Supported environments topic and the What's new in version 0.35.0 topic.
=> AIX Java 11+ requires XL C++ Runtime 16.1.0.7 or later

docs/jitserver_tuning.md, docs/version0.35.md, docs/xxjitservermetrics.md, docs/xxjitservermetricssslkey.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1000
Added -XX:JITServerMetricsSSLKey and -XX:JITServerMetricsSSLCert options Updated the related topics
=> Encryption of custom metrics exported by JITServer

docs/version0.35.md, docs/xxjitserverlocalsynccompiles.md
https://github.com/eclipse-openj9/openj9-docs/issues/1001
Updated the default status of the -XX:[+\-]JITServerLocalSyncCompiles option.
=> Default status of -XX:[+\-]JITServerLocalSyncCompiles

docs/openj9_support.md
https://github.com/eclipse-openj9/openj9-docs/issues/1008
Updated the "Eclipse OpenJ9 releases" table. Removed the note (1) saying that 0.35 is a future release. Added more future releases and removed older ones. Removed the "OpenJDK 18" sections.
Added RHEL9 to the list of supported platforms for Linux
=> Update supported platforms topic for 0.35.0

docs/gc_overview.md, docs/version0.35.md
https://github.com/eclipse-openj9/openj9-docs/issues/1017
Added information about the change in the GC behaviour in handling the phantom reference.
=> JSR 337 Maintenance Release 4 - Phantom reference

docs/jitserver.md, docs/jitserver_tuning.md, docs/version0.36.md, docs/xxjitserveraotmx.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1004
Updated the related documents with the new -XX:JITServerAOTmx option information.
=> JITServer AOT cache memory limit option

docs/xdump.md
The default `request` options for java dumps are `exclusive+preempt`, not `exclusive+prepwalk`:
```
-Xdump:java:
events=gpf+user+abort+traceassert+corruptcache,
file=javacore.%Y%m%d.%H%M%S.%pid.%seq.txt,
range=1..0,
priority=400,
request=exclusive+preempt
```
=> Fix -Xdump example to match javadump defaults

docs/version0.33.md, docs/version0.36.md, docs/xxjitserveraotcachename.md
https://github.com/eclipse-openj9/openj9-docs/issues/1026
Updated the default JITServer AOT cache name as 'default'
Please check in the draft docs at https://eclipse-openj9.github.io/openj9-docs-staging/1028/
=> Update the default JITServer AOT cache name

docs/jitserver.md, docs/jitserver_tuning.md, docs/version0.36.md, docs/xxjitserveraotcachedir.md, docs/xxjitserveraotcachename.md, docs/xxjitserveraotcachepersistence.md, docs/xxjitserveruseaotcache.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1025
Added information about the new options
-XX:[+|-]JITServerAOTCachePersistence
-Xjit:aotCachePersistenceMinDeltaMethods
-Xjit:aotCachePersistenceMinPeriodMs
-XX:JITServerAOTCacheDir
=> Document JITServer AOT cache persistence

docs/openj9_support.md, docs/version0.37.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1043
Updated the related topics with information regarding change in the compiler for AIX builds.
=> Move AIX compiles to 7.2

docs/openj9_support.md, docs/version0.37.md
Closes https://github.com/eclipse-openj9/openj9-docs/issues/1055
Updated the Visual Studio version used for compiling OpenJ9 Windows builds for OpenJDK 19 and later.
=> Build jdk19+ Windows with VS 2022

docs/xxjitserveraotcachepersistence.md
https://github.com/eclipse-openj9/openj9-docs/issues/1065
Fixed the broken link to -XX:JITServerAOTCacheName=<cache_name> topic by adding ".md" to the end of the file name
Closes: #1065
=> Fix broken link in the -XX:[+|-]JITServerAOTCachePersistence topic

docs/version0.37.md
https://github.com/eclipse-openj9/openj9-docs/issues/1056
Updated the What's new topic for version 0.37.0 release with the information related to adding of limited support for the com.sun.management.ThreadMXBean interface.
https://github.com/eclipse-openj9/openj9/issues/16772 - Created an issue in the code repo to update the 0.37.0 Release note as well.
=> Limited support for the com.sun.management.ThreadMXBean interface

docs/xlpobjectheap.md
https://github.com/eclipse-openj9/openj9-docs/issues/1064
Updated the section with the default page setting for z/OS and added a cross reference to the pageable|nonpageable section for more information.
=> Add zOS default settings under -Xlp:objectheap pagesize

JenkinsFile_build_doc.groovy
Avoid `fatal: unable to create threaded lstat` from `git status`
Closes https://github.com/eclipse-openj9/openj9/issues/16914
Tested in https://openj9-jenkins.osuosl.org/job/Build-Doc-Push_to_ghpages/184/ and it worked.
=> Modify build_doc to set git core.preloadIndex false

docs/version0.37.md, docs/xdump.md
https://github.com/eclipse-openj9/openj9-docs/issues/1033
Adding information of piped system dumps along with the new message JVMPORT0491
=> Linux piped core dump processing programs

docs/openj9_support.md, docs/version0.38.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1073
Updated the topics related to JDK8 build change.
Closes: #1073
=> JDK8 Windows compiles with VS2019

docs/cmdline_migration.md, docs/openj9_signals.md
Added the missing pipe symbol.
Related: #1084
=> Correct -XX:[+|-]HandleSIGABRT

docs/version0.37.md
https://github.com/eclipse-openj9/openj9-docs/issues/1087
What's new topic for 0.37.0 release updated.
Closes #1087
=> OpenJDK 19 for 0.37 is out of support

docs/interface_jvmti.md
Document the fact that these events run under the same restrictions as the GarbageCollectionStart/End events.
=> Document restrictions for the jvmtiVerboseGCSubscriber event

docs/version0.36.md, docs/version0.38.md
Updated the What's new in version 0.38.0 release with the information related to deprecation of support for running OpenJDK 8 and OpenJDK 11 on CentOS 6.10
=> Support on CentOS deprecated

docs/criusupport.md, docs/openj9_support.md, docs/version0.39.md
CRIU support is not available in version 0.39.0 release
JEPs for OpenJDK 20 added
OpenJDK 20 platform support details added. Modified the Build environments section as OpenJDK 20 and later
=> Updates based on 0.39.0 release changes

docs/version0.40.md, docs/xcodecachetotal.md, docs/xxcodecachetotal.md, docs/xxcodecachetotalmaxrampercentage.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1108
Created new topic for the new option and updated other related topics including the What's new in version 0.40.0 topic.
Closes #1108
=> Document new option -XX:codecachetotalMaxRAMPercentage

docs/criusupport.md, docs/xrsonrestoresynconrestore.md, docs/xshareclassesdisableonrestore.md, docs/xxcheckpointgcthread.md, docs/xxcriurestorenonportablemode.md, docs/xxenablecriusupport.md, docs/xxignoreunrecognizedrestoreoptions.md
https://github.com/eclipse-openj9/openj9-docs/issues/1092#issue-1688766829
Updated the topic with the information about when the VM client connects to a JITServer in the context of CRIU
Closes #1092
=> CRIU Support Documentation Updates for 0.40.0 release

docs/configuring.md
https://github.com/eclipse-openj9/openj9-docs/issues/1141
Corrected the default cache size and suggestion for IPCSHMMPAGES configuration on z/OS
=> Updated default cache size for IPCSHMMPAGES on z/OS

docs/openj9_support.md
Windows Server 2012 is out of support Oct 10, 2023
Closes https://github.com/eclipse-openj9/openj9-docs/issues/1149
Also change lists from "OpenjDK 20" to "OpenJDK 21" since 20 is out of support.
=> Remove Windows Server 2012 from supported platforms

docs/jitserver_tuning.md, docs/version0.41.md, docs/xshareclasses.md
https://github.com/eclipse-openj9/openj9-docs/issues/1145
Updated the -Xshareclasses:readonly topic and the JITServer AOT cache section in the JITServer tuning and practical considerations. Updated the What's new in version 0.42.0 topic.
Closes #1145
=> Changes to the behaviour of -Xshareclasses:readonly

docs/version0.41.md, docs/xxcontinuationcache.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1124
Created a new topic for the -XX:ContinuationCache option. Updated the What's new in version 0.41.0 topic.
Closes #1124
=> Documentation for -XX:ContinuationCache

docs/attachapi.md, docs/version0.41.md, docs/xxenabledynamicagentloading.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1140
Created a new topic for the -XX:[+|-]EnableDynamicAgentLoading option Updated the related topics.
Closes #1140
=> Documentation for -XX:[+|-]EnableDynamicAgentLoading

docs/version0.41.md, docs/xxusezlibnx.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1178
Created a new topic for -XX:[+|-]UseZlibNX. Updated the What's new in version 0.41.0
Closes #1178
=> Control loading of the zlibNX library on AIX with -XX:[+|-]UseZlibNX

CONTRIBUTING.md
https://github.ibm.com/runtimes/idteam/issues/1290
Updated all sundry issues listed in #1290 except for the MkDocs dependency change. This will be added in the Wiki page of the repository. Made some changes suggested by the Acrolinx.
=> Updating the Contribution topic

JenkinsFile_build_doc.groovy, docs/xtrace.md
Tracepoint types include "mem", not "eem".
Also tidied up spacing (removed internal tabs, trailing whitespace).
=> Fix typo in list of tracepoint types

docs/tool_jextract.md, docs/version0.42.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1183
Added a note in the Dump extractor (jpackcore) topic. Created the What's new topic for 0.42.0 release and added this change.
Closes #1183
=> jextract is removed from Java 21 and later

docs/version0.41.md
https://github.com/eclipse-openj9/openj9-website-publish/pull/6
Added the information related to improved algorithm with the use of OpenSSL version 3 and later
=> Improved algorithm with OpenSSL 3.0.12 and 3.1.4

docs/gc_overview.md, docs/version0.42.md
https://github.com/eclipse-openj9/openj9-docs/issues/1161
Updated the Garbage collection topic with the new behavior of the System.gc call.
Closes #1161
=> Ensure System.gc() triggers a GC and runs finalization

mkdocs.yml
Changes made in the yaml file to use Material's 'material.extensions.emoji.twemoji' and `material.extensions.emoji.to_svg` instead of `materialx.emoji.twemoji` and `materialx.emoji.to_svg`
=> Material emoji logic has been officially moved

docs/version0.41.md
https://github.com/eclipse-openj9/openj9-docs/issues/1199
Added the information related to threadAllocatedBytes MXBean API to What's new in version 0.42.0
Closes #1199
=> Add support for threadAllocatedBytes MXBean API

docs/dcomibmenablelegacydumpsecurity.md, docs/dcomibmenablelegacylogsecurity.md, docs/dcomibmenablelegacytracesecurity.md
https://github.ibm.com/runtimes/idteam/issues/1306
The term SecurityManager was misspelled as SecurityManger and the file name in the End of Topic comment was incorrect. Corrections made.
=> Correction of the term - SecurityManager

docs/migrating17to21.md, docs/version0.42.md, mkdocs.yml
Created a new topic - Migrating from Java 17 to Java 21 and included the JEPs for Java 21 in the What's new in version 0.42.0
=> Miscellaneous tasks for 0.42.0 release

docs/version0.41.md
https://github.com/eclipse-openj9/openj9-docs/issues/1199
Changed `getThreadAllocatedBytes MXBean` API to `com.sun.management.ThreadMXBean.getThreadAllocatedBytes()` API for consistency and clarity.
=> Content for support for threadAllocatedBytes MXBean API corrected

docs/version0.41.md
https://github.com/eclipse-openj9/openj9-docs/issues/1199
Changed `getThreadAllocatedBytes MXBean` API to
`com.sun.management.ThreadMXBean.getThreadAllocatedBytes()` API for consistency and clarity.
Port of https://github.com/eclipse-openj9/openj9-docs/pull/1220 for 0.41
=> (0.41) Content for support for threadAllocatedBytes MXBean API corrected

docs/version0.42.md, docs/xxiprofileduringstartupphase.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1204
Added a new topic for the new option, XX:[+/-]IProfileDuringStartupPhase. Updated the What's new in version 0.42.0 topic and the yaml file.
Closes #1204
=> Enforce/Disable IProfiler during startup phase

docs/version0.37.md, docs/version0.39.md, docs/version0.42.md
Changed http://openjdk.java.net to https://openjdk.org in topics.
=> Change http://openjdk.java.net to https://openjdk.org

docs/openj9_support.md, docs/version0.43.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1168
Updated the compiler details for Linux and Windows.
Closes #1168
=> Compile Windows with VS2022, x,p,zlinux to gcc 11.2 alinux to 10.3

JenkinsFile_build_container.groovy
I've only seen it fail on ub18-x86-1 but removing all ub18 just in case.
https://openj9-jenkins.osuosl.org/view/Website-Doc/job/Build-Doc-Docker_Container/15/
```
15:55:52  Err:1 http://archive.ubuntu.com/ubuntu jammy InRelease
15:55:52    The following signatures couldn't be verified because the
public key is not available: NO_PUBKEY 871920D1991BC93C
```
=> Don't build the docker container on ub18, it doesn't work

docs/configuring.md, docs/version0.43.md, docs/xlp.md, docs/xlpcodecache.md
https://github.com/eclipse-openj9/openj9-docs/issues/1206
Updated the related topics with the information of the change in the large page memory allocation behavior.
Closes #1206
=> Code cache allocation changes with Large pages enabled

docs/version0.43.md, docs/xxcompatibility.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1213
Added new topic for the new option, -XX:Compatibility=elasticsearch. Updated the What's new topic and mkdocs.yml file.
Closes #1213
=> New -XX:Compatibility=elasticsearch option

docs/jitserver.md, docs/version0.41.md
https://github.com/eclipse-openj9/openj9-docs/issues/1243
Updated related topics to document that support for JITServer on Linux on aarch64 was enabled in release-0.41
Closes #1243
=> Document support for JITServer on Linux on Aarch64

docs/jitserver.md, docs/version0.41.md
https://github.com/eclipse-openj9/openj9-docs/issues/1243
Updated related topics to document that support for JITServer on Linux on aarch64 was enabled in release-0.41
Cherry pick https://github.com/eclipse-openj9/openj9-docs/pull/1252 for 0.42
=> (0.42) Document support for JITServer on Linux on Aarch64

docs/criusupport.md
https://github.com/eclipse-openj9/openj9-docs/issues/1198
CRIU is supported only on Red Hat Universal Images (UBI) 8 and 9.
Closes #1198
=> CRIU Support on UBI 8 and 9

docs/enhancementstoopenjdksecurity.md
https://github.com/eclipse-openj9/openj9-docs/issues/1257
Updated with openCryptoki version 3.22 or later required  to generate RSA private keys with the ICA, CCA and EP11 tokens that opencryptoki supports.
Closes #1257
=> Creating RSA Private Keys with SunPKCS11 + Opencryptoki

docs/xxenabledynamicagentloading.md
https://github.com/eclipse-openj9/openj9-docs/issues/1264
Added a note in the existing topic -XX:[+|-]EnableDynamicAgentLoading that a fix to restrict the display of multiple warnings will be provided in a future release.
Closes #1264
=> JDK21+ AIX multiple warning messages

docs/xxenabledynamicagentloading.md
https://github.com/eclipse-openj9/openj9-docs/issues/1264
Added a note in the existing topic -XX:[+|-]EnableDynamicAgentLoading that a fix to restrict the display of multiple warnings will be provided in a future release.
Closes #1264
Same commit as https://github.com/eclipse-openj9/openj9-docs/issues/1264 merged to 0.43
=> (0.43) JDK21+ AIX multiple warning messages

docs/version0.43.md
Updated the support for `com.sun.management.ThreadMXBean.getThreadAllocatedBytes()` API added on z/OS platforms
=> Support for com.sun.management ThreadMXBean API on z/OS platforms

docs/version0.43.md
Support for com.sun.management ThreadMXBean API on z/OS platforms cherry picked and to be added to openj9-docs-0.43.0 branch
Port of https://github.com/eclipse-openj9/openj9-docs/pull/1274 for the 0.43 branch.
=> (0.43) Support for com.sun.management ThreadMXBean API on z/OS platforms

docs/version0.41.md, docs/version0.44.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1279
Deleted the reference to JDK 8 in Change in behavior of the `-Djava.security.manager` system property point in the What's new in version 0.41.0. Created the What's new in version 0.44.0 topic. Added that the change is now applicable on JDK 8 from 0.44.0 release onwards
Closes #1279
=> Ignore "allow" and "disallow" options in security manager on jdk8

docs/version0.44.md, docs/xxenabledynamicagentloading.md
https://github.com/eclipse-openj9/openj9-docs/issues/1264
Fix added to restrict display of multiple warnings on loading the same agent on AIX
Closes #1264
=> Single warning message if the same library loaded-AIX

docs/openj9_support.md, docs/version0.44.md
https://github.com/eclipse-openj9/openj9-docs/issues/1280
Updated that AIX OpenJ9 builds require the [XL C++ Runtime 16.1.0.7 or later on Java 8
Closes #1280
=> Compile AIX jdk8 with xlclang 16.1

docs/cmdline_migration.md
https://github.com/eclipse-openj9/openj9-docs/issues/1282
Option removed from the "Creating compatible behavior" table. From 0.41 the default behavior is compatible for this option.
Closes #1282
=> -XX:+CompactStrings is default since 0.41

.vscode/settings.json, docs/version0.44.md, docs/xxcodecachetotalmaxrampercentage.md, docs/xxcontinuationcache.md, docs/xxshowunmountedthreadstacks.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1241
Added a new topic for the new option, -XX:[+|-]ShowUnmountedThreadStacks
Closes #1241
=> Document new -XX:[+|-]ShowUnmountedThreadStacks option

.gitignore, docs/dcomibmtoolsattachdisplayname.md, docs/tool_jcmd.md, docs/tool_migration.md, docs/version0.44.md
https://github.com/eclipse-openj9/openj9-docs/issues/1292
Updated the related topics with the change in jcmd VMID query behavior
Closes #1292
=> jcmd supports VMID query via Java process display name

docs/shrc.md, docs/xscmx.md, docs/xshareclasses.md
https://github.com/eclipse-openj9/openj9-docs/issues/1298
Added z/OS in list of platforms that support persistent shared cache
Closes #1298
=> Persistent shared caches are supported on z/OS

docs/version0.44.md
https://github.com/eclipse-openj9/openj9-docs/issues/1306
The change is explained in the What's new in version 0.44.0 topic.
Closes #1306
=> Document changes to writing DDR extensions

docs/dcomibmtoolsattachfileaccessupdatetime.md, docs/version0.44.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1310
Created a new topic for the -Dcom.ibm.tools.attach.fileAccessUpdateTime system property. Updated the What's new in 0.44.0 version
Closes #1310
=> Document -Dcom.ibm.tools.attach.fileAccessUpdateTime system property

docs/shrc.md
Included information about the release when the support for persistent shared classes cache was added on z/OS.
=> Persistent shared classes cache support on z/OS

docs/xxusegcstartuphints.md
https://github.com/eclipse-openj9/openj9-docs/issues/1319
Added a clarification about the overriding heap size value.
Closes #1319
=> Overridden GC hint value for -Xms clarification

docs/openj9_support.md
Add "or later" to the jdk21 list of supported platforms, similarly to the build environments.
=> Indicate the supported platforms for jdk22

docs/attachapi.md
https://github.com/eclipse-openj9/openj9-docs/issues/1307
Documented how to prevent a user from interfering with the AttachAPI functioning through file permission modification.
Closes #1307
=> Securing the Attach API

docs/djdknativecrypto.md, docs/djdknativedigest.md, docs/djdknativeeckeygen.md, docs/djdknativexdhkeyagreement.md, docs/djdknativexdhkeygen.md, docs/version0.46.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1322
Acceleration is added for MD5 message digest and the related topics are updated.
Closes #1322
=> OpenSSL MD5 message digest acceleration

docs/version0.46.md
https://github.com/eclipse-openj9/openj9-docs/issues/1326
Updated the What's new in version 0.46.0 topic.
Closes #1326
=> ThreadMXBean.getTotalThreadAllocatedBytes is implemented

docs/xshareclasses.md
The MAXSHARE option controls the amount of storage that can be used for mmap64. This parameter applies on a per address space level. We can reduce the current recommendation of 1GB to 300MB to better align with the SCC default usage requirements. Also, add text to discuss JOBNAME filter and suppression of IEF043I diagnostic messsages from appearing.
=> Update z/OS MAXSHARE recommendations for persistent shared cache

docs/openj9_support.md
https://github.com/eclipse-openj9/openj9-docs/issues/1357
Added a note to say that JDK 22 is supported only on macOS 12-14. Added support on macOS 14 in all versions
Closes #1357
=> JDK 22 supported only on macOS 12-14

docs/version0.46.md, docs/xxenableextendedhcr.md
https://github.com/eclipse-openj9/openj9-docs/issues/1352
New option -XX:[+|-]EnableExtendedHCR added.
Closes #1352
=> Add option to toggle Extended HCR capability

mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1352
-XX:[+|-]EnableExtendedHCR option added to the TOC
Closes #1352
=> -XX:[+|-]EnableExtendedHCR added to TOC

buildenv/requirements.txt
mkdocs build is failing because ibm-cos-sdk-core 2.13.6 requires python-dateutil<3.0.0,>=2.9.0, but the current python-dateutil is 2.8.2 which is incompatible.
=> Python-dateutil update

docs/attachapi.md, docs/dcomibmtoolsattachretry.md, docs/version0.46.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1313
Added the new system property -Dcom.ibm.tools.attach.retry. Updated related topics.
Closes #1313
=> New system property -Dcom.ibm.tools.attach.retry

docs/version0.46.md, docs/xxshareorphans.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1330
New option `-XX:[+|-]ShareOrphans` added. Related topics updated.
Closes #1330
=> New option to store classes from all class loaders

buildenv/requirements.txt
Build_mkdocs_for_kc_no_Docker build was failing because of the following errors:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. softlayer 6.2.4 requires requests>=2.32.2, but you have requests 2.32.0 which is incompatible. 
Tried updating to 2.32.3  as per the latest mkdocs dependencies level but encountered the following error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. ibm-cos-sdk-core 2.13.6 requires requests<2.32.3,>=2.32.0, but you have requests 2.32.3 which is incompatible.
So, updated the requests version to 2.32.2. Tested and …
=> Updated the requests version in requirements.txt

docs/version0.46.md, docs/xxjitserveraotcacheignorelocalscc.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1379
Added content related to new option  -XX:[+|-]JITServerAOTCacheIgnoreLocalSCC. Updated the related topics also.
Closes #1379
=> Document option -XX:[+|-]JITServerAOTCacheIgnoreLocalSCC

docs/interface_dtfj.md
Java 9 and above has deprecated Class.newInstance in favor of Class.getDeclaredConstructor().newInstance:
https://docs.oracle.com/javase/9/docs/api/java/lang/Class.html#newInstance--
The DTFJ examples use the old form which causes the following compilation warnings:
```
DTFJVendorCheck.java:55: warning: [deprecation] newInstance() in Class has been deprecated
ImageFactory factory = (ImageFactory) factoryClass.newInstance();
^
where T is a type-variable:
T extends Object declared in class Class
DTFJVendorCheck.java:55: warning: [unchecked] unchecked call to getDeclaredConstructor(Class<?>...) as a member of the raw type Class
ImageFactory factory = (ImageFactory) factoryClass.getDeclaredConstructor().newInstance();
^
where T is a type-variable:
T extends Object declared in class Class
``` …
=> Fix DTFJ example compilation warning on Java > 8

docs/version0.47.md, docs/xxshareorphans.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1354
-Xshareclasses now automatically turns on -XX:+ShareOrphans
Closes #1354
=> -Xshareclasses automatically turns on -XX:+ShareOrphans

docs/version0.47.md, docs/xxshareorphans.md
Two of the restrictions fixed in 0.47.0 release and therefore removed in the related topic.
=> Restrictions in the `-XX:[+|-]ShareOrphans` option removed

docs/version0.46.md
Added RHEL 9.2 as the new minimum operating system level and changed the supported platform sentence for clarity.
=> What's new in version 0.46.0 update

docs/version0.46.1.md
Link corrected
Cherry pick of https://github.com/eclipse-openj9/openj9-docs/pull/1404
=> (0.46.1) Release 0.46.1 What's new-Link correction

docs/xtrace.md
See https://github.com/eclipse-openj9/openj9/issues/20175
=> Add missing tracepoint components and groups

docs/xtrace.md
Related to https://github.com/eclipse-openj9/openj9-docs/pull/1413
=> Fix typo in list of -Xtrace components

buildenv/requirements.txt
Reverted MkDocs version from 1.6.1 to 1.5.3 and changed the mkdocs-material from 9.5.34 to 9.5.29 to correct the duplicate TOC entries.
=> Revert MkDocs version 1.6.1 to 1.5.3

docs/version0.48.md, docs/xxusezlibnx.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1426
Updated the related topics with the change in the default behavior related to the zlibNX library.
Closes #1426
=> Disable zlibNX onAIX by default

buildenv/Dockerfile
Related to the Nov 15, 2024 change in Docker's subscription model, and ease of building the image at companies building the docs image for testing.
I tried building locally using the instructions at https://github.com/eclipse-openj9/openj9-docs/wiki/Testing-OpenJ9-MkDocs-dependencies and it worked.
=> Pull the Ubuntu 22.04 image from Amazon instead of Dockerhub

docs/interface_jvmti.md, docs/version0.48.md, docs/xrunjdwp.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1407
Added the -Xrunjdwp option with the new SuspendOnRestore parameter.
Closes #1407
=> CRIU enable JDWP support post-restore

docs/openj9_support.md, docs/version0.49.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1451
Removed macOS 12 from the list of supported environments.
Closes #1451
=> MacOS 12 is out of support

docs/version0.49.md
https://github.com/eclipse-openj9/openj9-docs/issues/1406
Added the change in the shared class cache generation number in the What's new in version 0.49.0 topic.
Closes #1406
=> Shared class cache generation update

docs/version0.49.md, docs/xshareclasses.md
https://github.com/eclipse-openj9/openj9-docs/issues/1433
New parameter 'extraStartupHints` added to the -Xshareclasses topic.
Closes #1433
=> New CML option to adjust storage of extra startup hints

buildenv/requirements.txt
MkDocs Build failure because of dependency conflict. poetry 2.0.0 requires packaging>=24.0, instead of 23.2 which is incompatible. Updated the packaging version
=> Fix for MkDocs Build failure

docs/allocation.md, docs/version0.49.md, docs/xgc.md, docs/xmcrs.md
https://github.com/eclipse-openj9/openj9-docs/issues/1418
Added new `-Xgc` suballocator options in related topics.
Closes #1418
=> Add documentation for -Xgc suballocator options

docs/version0.49.md, docs/xxflightrecorder.md
Incorporated the review comments related to JFR in another issue
=> Updated the -XX:[+|-]FlightRecorder` option

docs/dump_javadump.md
https://github.com/eclipse-openj9/openj9-docs/issues/1486
Added content to clarify the type of memory usage reported in the NATIVEMEMINFO section.
Closes #1486
=> Clarify Java Dump NATIVEMEMINFO section

docs/api-overview.md, docs/introduction.md, docs/version0.46.md
https://github.com/eclipse-openj9/openj9-docs/issues/1504
OpenJ9 0.46.0 introduced a new Data Access Accelerator library class and API: com/ibm/dataaccess/ExternalDecimal.checkExternalDecimal. This is documented in 0.51.0 release.
Closes #1504
=> Document new DAA api added in 0.46.0

CONTRIBUTING.md, docs/openj9_support.md, docs/version0.51.md, mkdocs.yml
https://github.com/eclipse-openj9/openj9-docs/issues/1498
Updated the Supported environments topic.
Closes #1498
=> AIX compiler updated to 16.1.0.20, Runtime required is 16.1.0.10

docs/djdknativecrypto.md, docs/djdknativeecdsa.md, docs/djdknativepbe.md, docs/openssl.md, docs/version0.51.md, mkdocs.yml
Updated the OpenSSL topic with ECDSA signature algorithm and PBE cipher support for OpenSSL.
=> Security documentation change - ECDSA and PBE

docs/version0.51.md, docs/xxflightrecorder.md
https://github.com/eclipse-openj9/openj9-docs/issues/1515
Added content for full platform support for JFR.
Closes #1515
=> Full platform support for JFR

docs/xdump.md
https://github.com/eclipse-openj9/openj9-docs/issues/1530
Updated the -Xdump topic with the additional content for clarity.
Closes #1530
=> Clarify request=exclusive for user and slow events

buildenv/requirements.txt
Pip's dependency conflict resolution. selenium 4.34.1 requires certifi>=2025.6.15.
=> Update Requirements.txt - certifi update

docs/xxflightrecorder.md
https://github.com/eclipse-openj9/openj9-docs/issues/1545
Updated the -XX:[+|-]FlightRecorder topic.
Closes #1545
=> Update JFR status statement

docs/version0.53.md, docs/xxflightrecorder.md
https://github.com/eclipse-openj9/openj9-docs/issues/1560
Added the new events  of JFR.
Closes #1560
=> Update 0.53 release notes

docs/xxidletuningcompactonidle.md, docs/xxidletuninggconidle.md
[#1601](https://github.com/eclipse-openj9/openj9-docs/issues/1601)
Added macOS and z/OS to the options topics.
Closes [#1601](https://github.com/eclipse-openj9/openj9-docs/issues/1601)
=> -XX:IdleTuningGcOnIdle, -XX:IdleTuningCompactOnIdle on mac, zos
